### ISSUE TITLE
Consider Jib packaging type

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#1105]
We added a `jib.skip` property to deal with `jib:build` in a multi-module setup (#865 and #911).  An alternative would be to create a custom `jib` packaging type that would incorporate one of our jib goals as part of the Maven lifecycle, and thus eliminate the need to explicitly invoke `jib:*`.

[Creating a custom packaging](https://books.sonatype.com/mvnref-book/reference/writing-plugins-sect-plugins-lifecycle.html) is [relatively straight-forward](https://stackoverflow.com/questions/1427722/how-do-i-create-a-new-packaging-type-for-maven), and mapping to the [maven-jar-plugin](https://github.com/apache/maven-jar-plugin/blob/master/src/main/filtered-resources/META-INF/plexus/components.xml) is pretty straightforward too.  Except there's a bit of a conflict in the default expectations of the `package`, `install`, and `deploy` lifecycle phases and effects of Jib build options: `package` is generally entirely local, `install` installs to local ~/.m2/repository, and `deploy` (upload somewhere).  One possible mapping might be:

  - `package`: `buildTar` 
  - `install`: `dockerBuild` &larr; load to the local docker daemon
  - `deploy`: `build`

Another possibility is to introduce new Jib goals for `install` and `deploy` that load the built-tar container into the local docker daemon or upload to a registry.

Or another alternative is to define a single new Jib goal used for `package` whose build action is determined by a property.  Say `jib:package` which uses the `jib.destination` property that defines `tar`, `daemon`, or `registry`.

**Comment by coollog** [comment]
Perhaps we could even define separate packaging for the different destination types: `jib` as to registry, `jib-docker` as to Docker daemon, and `jib-tar` as to tarball.

**Comment by briandealwis** [comment]
What would you see as their phase mappings to the maven lifecycle?  I wondered about it too.

I think the single `jib` packaging could work if coupled with `skipTar`, `skipLocalDaemon` and `skipRegistry` properties. Or maybe a single comma-separated property.

**Comment by xlf12** [comment]
> Perhaps we could even define separate packaging for the different destination types: `jib` as to registry, `jib-docker` as to Docker daemon, and `jib-tar` as to tarball.

I would like to stay as close as possible to the original abstraction maven introduced, which IMHO means ...

The destination is driving force behind the phases `package`,  `install` and `deploy`, as already stated in the issue description.  So a  jib tar on the local disk  is only the outcome of the package phase. 

The property `format` with the values  `docker` or `OCI` would be IMHO worth a specific package format because it changes the content of the produced package.

**Comment by xlf12** [comment]
> What would you see as their phase mappings to the maven lifecycle? I wondered about it too.
> 
> I think the single `jib` packaging could work if coupled with `skipTar`, `skipLocalDaemon` and `skipRegistry` properties. Or maybe a single comma-separated property.

IMHO if something is bound implicit to the Maven life cycle we need this `skipXYZ` switches anyway because there will be always a use case where you might want to execute a specific phase for example deploy, which means deploy all old school Maven artifacts but you skip the foo stuff.  

Otherwise you must immediately fallback to use Maven profiles which is more verbose but even more flexible. 

Maybe it is important to mention that we often use multi module builds where a lot of old school jars and assemblies exists beside the new jib artifacts.  These jib projects are dedicated sub-module assembly projects.

**Comment by m86194** [comment]
As the goals usually are exclusive (you don't want a tar, deploy to local docker and a registry in the same build) I think it would be better to provide clear instructions on how to bind to the Maven build cycle.

A thing that may be easy to do, is to have "buildTar" generate the docker image as the build artifact, which can then be pushed to a maven registry and treated like any other artifact.  This may be an interesting alternative to moving images around for existing Java pipelines.

**Comment by loosebazooka** [comment]
I think we are going to shelve this for now. Users wanting to integrate into the maven lifecycle can do so in their pom, disable the deploy and install tasks.
