### ISSUE TITLE
Consider providing JibExtension setters as methods.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#1122]
Original comment: https://github.com/GoogleContainerTools/jib/issues/1060#issuecomment-428446526

> Thanks! This also fixes the issue I am having. The Gradle Kotlin DSL syntax for collections is still a little bit unpleasant. It requires writing something like `jib.container.jvmFlags = listOf(...)`. It would be nice if this were just `jib.container.jvmFlags(...)`, where the method took vararg parameters.

**Comment by diendanyoi54** [comment]
@coollog looks like this issue was created because you're having issues with accessing this stuff when attempting to set these fields in Kotlin?  I've attempted to create a custom plugin using Kotlin and have no access to any classes themselves in **_com.google.cloud.tools.jib.gradle_**.
![Screenshot_20191104_111420](https://user-images.githubusercontent.com/17833452/68142425-6cf9c500-fefd-11e9-8a4e-11e41f9df18b.png)

When trying to build my custom plugin using gradle I actually receive an `Unresolved reference: cloud` because I'm unable to reach the **_package com.google.cloud_**.

**Comment by chanseokoh** [comment]
@diendanyoi54 I don't know anything about developing a Kotlin plugin, but are you putting these imports into `build.gradle.kts`? jib-gradle-plugin (everything under com.google.cloud.tools.jib.gradle) is not a library for consumption.

**Comment by diendanyoi54** [comment]
@chanseokoh no, it's a standalone plugin that I'm importing into other projects to consolidate common task configurations so my build.gradle.kts are not enormous in each microservice and to prevent copy pasta.  This link more describes what I'm trying to accomplish https://stackoverflow.com/questions/58274271/how-to-consolidate-imported-plugins-to-custom-plugin-in-gradle-using-kotlin.  Because jib-gradle-plugin is not for consumption, does this prevent me from being able to accomplish this?

**Comment by chanseokoh** [comment]
I am no Gradle expert. I just wonder if you can use a simpler approach to to share configurations than creating a custom plugin? This question lists [some possibilities](https://stackoverflow.com/questions/9539986/how-to-share-a-common-build-gradle-via-a-repository) (and one of them included creating a custom plugin as an option).

**Comment by diendanyoi54** [comment]
The only other option looks to be the apply(from = url), which would be a great alternative, but our nexus instance requires https with creds so I get `401 Unauthorized`

**Comment by chanseokoh** [comment]
How about https://stackoverflow.com/a/50546335? There are people who read credentials from Maven's `settings.xml`. Not sure if there are better ways than the answers in the SO question these days though.

**Comment by chanseokoh** [comment]
@diendanyoi54 I just came across this and wondered if it is relevant: https://stackoverflow.com/questions/58758685/how-can-i-configure-the-jib-extension-inside-a-buildsrc-kotlin-file To me, the user is trying something very similar.

**Comment by loosebazooka** [comment]
@diendanyoi54 How are you including the jib gradle plugin into your classpath?

**Comment by diendanyoi54** [comment]
@loosebazooka my boss was able to point me in the direction you mentioned and that was my issue.  I was trying to bring plugins in via the typical 'modern' way by just using `plugins {}` instead of 
```
repositories {
    maven { url = uri("https://plugins.gradle.org/m2/") } // This is required to be able to import plugins below in the dependencies
    jcenter()
}

dependencies {
    compile(kotlin("stdlib"))
    compile(kotlin("reflect"))
    compile(group = "gradle.plugin.com.google.cloud.tools", name = "jib-gradle-plugin", version = "1.7.0")

    implementation(gradleApi()) // This exposes the gradle API to CustomPlugin.kt
}
```

**Comment by diego92sigma6** [comment]
Closing - issue was solved
