### ISSUE TITLE
[gradle] Allow programatically setting base layer cache directory

### ISSUE THREAD

**Issue by anuraaga** [GoogleContainerTools/jib#1238]
**Description of the issue**: It would be convenient to be able to set the base layer cache directory programatically, for example to set it to `project.getGradle().getGradleUserHomeDir()` to keep it together with other gradle caches if desired.

**Expected behavior**: Currently, it seems to only be possible to either say yes/no to project-level cache, or use the environment variable XDG_CACHE_HOME. It is often difficult to set an environment variable programatically or in a way that allows reproducible builds (e.g. applies to both CI and dev machines).

**Environment**: gradle-jib-plugin

**Comment by coollog** [comment]
Hi @anuraaga , thanks for the suggestion! We'll consider adding this since it does enable better control over caches across multiple machines. However, one thing we do wish to avoid is to enable bad practices like placing full paths in a `pom.xml` where the full paths are specific to a single machine and not portable across machines.

**Comment by coollog** [comment]
We may wish to also allow changing the application layers cache for users who wish to `clean` upon each build but not always clear the `jib-cache`.
