### ISSUE TITLE
[gradle] Non-existent extra source set directories cause build to fail

### ISSUE THREAD

**Issue by anuraaga** [GoogleContainerTools/jib#1271]
**Description of the issue**: When the project registers extra source set directories but the folder doesn't exist, the build fails with

```
Step #3 - "curio-generated-build-all": Caused by: com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build image failed
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build(BuildStepsRunner.java:269)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:119)
Step #3 - "curio-generated-build-all": at jdk.internal.reflect.GeneratedMethodAccessor804.invoke(Unknown Source)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #3 - "curio-generated-build-all": at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
Step #3 - "curio-generated-build-all": ... 50 more
Step #3 - "curio-generated-build-all": Caused by: java.nio.file.NoSuchFileException: /workspace/frontend/server/src/main/proto
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.LayerEntriesSelector$LayerEntryTemplate.<init>(LayerEntriesSelector.java:72)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.LayerEntriesSelector.toSortedJsonTemplates(LayerEntriesSelector.java:129)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.LayerEntriesSelector.generateSelector(LayerEntriesSelector.java:145)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.Cache.retrieve(Cache.java:98)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:107)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:37)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
```

**Expected behavior**: The image build succeeds because a non-existent directory is not a fatal error (even if it does indicate a possible project misconfiguration)

**Steps to reproduce**:

```bash
git clone https://github.com/anuraaga/jib-issue-1271
cd jib-issue-1271
./gradlew jibBuildTar
```

**Environment**: Linux, Gradle 5.0-rc-4, Java 11, gradle-jib-plugin 0.10.0

**`jib-gradle-plugin` Configuration**:
```groovy
apply plugin: 'com.google.protobuf'
apply plugin: 'com.google.cloud.tools.jib'
```

**Log output**: 

```
Step #3 - "curio-generated-build-all": Caused by: com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build image failed
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build(BuildStepsRunner.java:269)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:119)
Step #3 - "curio-generated-build-all": at jdk.internal.reflect.GeneratedMethodAccessor804.invoke(Unknown Source)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #3 - "curio-generated-build-all": at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
Step #3 - "curio-generated-build-all": ... 50 more
Step #3 - "curio-generated-build-all": Caused by: java.nio.file.NoSuchFileException: /workspace/frontend/server/src/main/proto
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.LayerEntriesSelector$LayerEntryTemplate.<init>(LayerEntriesSelector.java:72)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.LayerEntriesSelector.toSortedJsonTemplates(LayerEntriesSelector.java:129)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.LayerEntriesSelector.generateSelector(LayerEntriesSelector.java:145)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.Cache.retrieve(Cache.java:98)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:107)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:37)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
```

**Additional Information**:

**Comment by briandealwis** [comment]
Hi @anuraaga — I'm not able to reproduce this with Jib 0.10.0 and Gradle 4.10.2.  Can you provide a tiny standalone example?

**Comment by anuraaga** [comment]
Sure! Will set up a repo for it within the next couple of days, sorry for not doing so when reporting. Admittedly I abstracted away some of the ways we use the protobuf plugin hoping the stacktrace might be obvious but guess it wasn't so trivial 😹

**Comment by spud22** [comment]
On Nov 21, 2018 10:54 PM, "Anuraag Agrawal" <notifications@github.com>
wrote:

*Description of the issue*: When the project registers extra source set
directories but the folder doesn't exist, the build fails with

Step #3 - "curio-generated-build-all": Caused by:
com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException:
Build image failed
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build(BuildStepsRunner.java:269)
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:119)
Step #3 - "curio-generated-build-all": at
jdk.internal.reflect.GeneratedMethodAccessor804.invoke(Unknown Source)
Step #3 - "curio-generated-build-all": at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #3 - "curio-generated-build-all": at
org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
Step #3 - "curio-generated-build-all": ... 50 more
Step #3 - "curio-generated-build-all": Caused by:
java.nio.file.NoSuchFileException:
/workspace/frontend/server/src/main/proto
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.cache.LayerEntriesSelector$LayerEntryTemplate.<init>(LayerEntriesSelector.java:72)
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.cache.LayerEntriesSelector.toSortedJsonTemplates(LayerEntriesSelector.java:129)
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.cache.LayerEntriesSelector.generateSelector(LayerEntriesSelector.java:145)
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.cache.Cache.retrieve(Cache.java:98)
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:107)
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:37)
Step #3 - "curio-generated-build-all": at
com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
Step #3 - "curio-generated-build-all": at
com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
Step #3 - "curio-generated-build-all": at
com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)

*Expected behavior*: The image build succeeds because a non-existent
directory is not a fatal error (even if it does indicate a possible project
misconfiguration)

*Steps to reproduce*:

Apply protobuf plugin without creating a proto source directory and run jib

*Environment*: Gradle, Linux

*jib-gradle-plugin Configuration*:

apply plugin: 'com.google.protobuf'
apply plugin: 'com.google.cloud.tools.jib'

*Log output*:

Step #3 - "curio-generated-build-all": Caused by:
com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException:
Build image failed
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build(BuildStepsRunner.java:269)
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:119)
Step #3 - "curio-generated-build-all": at
jdk.internal.reflect.GeneratedMethodAccessor804.invoke(Unknown Source)
Step #3 - "curio-generated-build-all": at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #3 - "curio-generated-build-all": at
org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
Step #3 - "curio-generated-build-all": ... 50 more
Step #3 - "curio-generated-build-all": Caused by:
java.nio.file.NoSuchFileException:
/workspace/frontend/server/src/main/proto
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.cache.LayerEntriesSelector$LayerEntryTemplate.<init>(LayerEntriesSelector.java:72)
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.cache.LayerEntriesSelector.toSortedJsonTemplates(LayerEntriesSelector.java:129)
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.cache.LayerEntriesSelector.generateSelector(LayerEntriesSelector.java:145)
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.cache.Cache.retrieve(Cache.java:98)
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:107)
Step #3 - "curio-generated-build-all": at
com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:37)
Step #3 - "curio-generated-build-all": at
com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
Step #3 - "curio-generated-build-all": at
com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
Step #3 - "curio-generated-build-all": at
com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)

*Additional Information*:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GoogleContainerTools/jib/issues/1271>, or mute the
thread
