### ISSUE TITLE
Build an image without having to deploy it

### ISSUE THREAD

**Issue by Xnyle** [GoogleContainerTools/jib#1276]
Sorry If this is a stupid question: Is there no way to just build an image without having to deploy it to a remote hub?
**to** is mandatory, but i couldn't figure out how to just set it to some local path.

**Comment by TadCordle** [comment]
The two local options are `jibDockerBuild` (gradle)/`jib:dockerBuild` (maven) for building to the Docker daemon, and `jibBuildTar` (gradle)/`jib:buildTar` (maven) for building a .tar file to the project's build directory (this path isn't configurable by jib).

The reason `to` is required even for local builds is because the value in `to` is the image name that is displayed when it's loaded by docker. However, I believe jib automatically resolves the project name/version if you leave it blank when doing a local build, if the project name/version are configured.

**Comment by Xnyle** [comment]
Thanks, I read over jib:buildTar 3 times. Maybe make a h1 out of "Build an image tarball" in the markdown.
