### ISSUE TITLE
Jib should use the Main-Class as specified in a MANIFEST.MF

### ISSUE THREAD

**Issue by kameshsampath** [GoogleContainerTools/jib#1470]
**Description of the issue**:
When I use jib with a vert.x project, jib is not able to extract the mainClass from the MANIFEST.MF, instead fails with `mainClass` not defined error

**Expected behaviour**:
The mainClass attribute should be extracted from MANIFEST.MF

**Steps to reproduce**: 
1. clone the project https://github.com/kameshsampath/vertx-jib-example
2. Update the configuration to point to your docker registry (https://github.com/kameshsampath/vertx-jib-example/blob/master/pom.xml#L69)
3. run mvn package  jib:build 

**Environment**:  macOS, maven 3.6.0 and JDK 1.8

**`jib-maven-plugin` Configuration**: 
```xml
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>jib-maven-plugin</artifactId>
        <version>1.0.0</version>
        <configuration>
          <allowInsecureRegistries>true</allowInsecureRegistries>
          <container>
            <!-- need to add this , though the manifest has the Main-Class: io.vertx.core.Launcher -->
            <!--<mainClass>io.vertx.core.Launcher</mainClass>-->
          </container>
          <to>
            <credHelper>osxkeychain</credHelper>
            <!-- Replace the repo id   -->
            <image>kameshsampath/vertx-helloworld</image>
          </to>
        </configu
```

**Log output**: 
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.0.0:build (default-cli) on project vertx-jib-example: Main class was not found, perhaps you should add a `mainClass` configuration to jib-maven-plugin -> [Help 1]
```
**Additional Information**:

**Comment by chanseokoh** [comment]
Jib does not depend on building a JAR and doesn't open, read, or make any use of the built JAR. The presence of a JAR is irrelevant. In fact, `mvn compile` rather than `mvn package` is sufficient to containerize the app.

Technically it is possible to make Jib depend on `mvn package` and unzip the built JAR. However, we are not yet convinced to do so only because we may need to unzip the JAR for a possible entry in `MANIFEST.MF`. From Jib's perspective, packaging a deployable app as a container is at odds with packaging it as a JAR, and we've been consciously setting any JAR-packaging stuff apart from our direct containerization. Our initial intention with Jib was not to support containerizing a JAR. Check [this comment](https://github.com/GoogleContainerTools/jib/issues/1280#issuecomment-442255523) and [this FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-want-to-containerize-an-executable-jar) for this opinionated approach of Jib. (That said, we do have an open issue (a feature request) to directly embed a build JAR: #530.)

For this reason, I recommend explicitly setting `<mainClass>`, which will also signify that Jib won't make any use of the built JAR. Making whatever changes to the JAR has no effect on Jib's output.

**Comment by chanseokoh** [comment]
However, I'll leave this open for the possibility that we may make a decision to read `MAMIFEST.MF` from a JAR in the future.

**Comment by briandealwis** [comment]
Marking as P4 as we provide ways to describe the main-class.

If we did go down this route, would there be an expectation to support other settings from the maven-archive-plugin's [spec](https://maven.apache.org/shared/maven-archiver/index.html)?

**Comment by andxu** [comment]
@chanseokoh shall jib guess the main class based on some rules? like only one main class is found in src folder?

**Comment by chanseokoh** [comment]
@andxu Jib is already looking into all class files to find main methods and automatically picks up a main if there exists only one.

**Comment by m86194** [comment]
@kameshsampath 

> When I use jib with a vert.x project, jib is not able to extract the mainClass from the MANIFEST.MF, instead fails with `mainClass` not defined error

Normally the manifest entry is _only_ read when invoking with `java -jar foo.jar` which implies a lot of other functionality (like setting up the classpath etc).   This implies that instead of invoking with "java -cp... " you want to invoke with "java -jar" instead.  Does this fix your problem?

**Comment by cmoulliard** [comment]
I'm also having the same issue if we pass the parameter `-f` to maven

```
mvn -f /home/jboss/quarkus-demo/pom.xml compile com.google.cloud.tools:jib-maven-plugin:2.0.0:build -Djib.from.image=registry.redhat.io/redhat-openjdk-18/openjdk18-openshift -Dimage=172.30.1.1:5000/test/quarkus-demo
...
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.0.0:build (default-cli) on project quarkus-rest: Main class was not found, perhaps you should add a `mainClass` configuration to jib-maven-plugin -> [Help 1]

```

**Comment by chanseokoh** [comment]
@cmoulliard I don't think the parameter `-f` is relevant. Does `/home/jboss/quarkus-demo/pom.xml` define `<mainClass>`?

(BTW, Quarkus doesn't really work with Jib.)

**Comment by briandealwis** [comment]
In #2268  (19989bb08dff3c90f16cb7b27aec9d76503ff80c) I added support to pull the main-class from the locations supported by the `native-image-maven-plugin`. This could be generalized and used here.

**Comment by loosebazooka** [comment]
dup of #1503
