### ISSUE TITLE
Create time of building docker images using Jib

### ISSUE THREAD

**Issue by tankdeper** [GoogleContainerTools/jib#1562]
**Description of the issue**:  I used `jib` to build up my java application as docker image, when I pull request from docker, I found that the `creatime` is extremely ridiculous, it shows `49 years ago`

**Expected behavior**: it should be the same or similar to the time as I built

**Steps to reproduce**: 

**Environment**: windows10, Maven

**Log output**:  
```zhengtank/hello-world                                  latest              5fc7a163adf7        49 years ago        102MB```

**Additional Information**:  You all could pull request this image from registry.hub.docker.com, and you'll see `49 years ago`

**Comment by TadCordle** [comment]
Jib strips timestamps in order to maintain reproducibility. You can bypass this behavior by setting the `container.useCurrentTimestamp` configuration parameter to `true`. See the [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#why-is-my-image-created-48-years-ago) for more details.

**Comment by tankdeper** [comment]
@TadCordle Excuse me! Could you please explain what reproducibility means and what kind of situation we need this?

**Comment by chanseokoh** [comment]
@tankdeper say that you ran `mvn jib:dockerBuild` with `<container><userCurrentTimestamp>true`. It will build an image whose creation time is the current timestamp. Now, a few seconds later, you run `mvn jib:dockerBuild` again without changing anything in your project. That is, the image created by the second `mvn jib:dockerBuild` build is identical to the first image except the timestamp. However, because the two images have different timestamps, tools, systems, and infrastructures (Docker daemon, Docker Hub, registries, ECR, Kubernetes, etc) will see the two as different images. For example, now `docker images` will list two images, whereas without `<useCurrentTimestamp>`, the Docker daemon would have thought that the image already existed and resulted in no-op. Likewise, when you push the second image to a remote registry, the registry will see that as a new image that doesn't exist. Tools will think it is a different image and download it again and cache it as a different image, even if it is the exactly same image except the timestamp. So, running `mvn jib:dockerBuild` multiple times is not a reproducible build in the sense that it doesn't create the same image each time.

**Comment by tankdeper** [comment]
Thanks a lots! Running `mvn jib:build` is the same to this, right?

**Comment by chanseokoh** [comment]
@tankdeper yeah, without `<useCurrentTimestamp>`, you always build the same, reproducible image regardless of how many times you run either `jib:build` or `jib:dockerBuild`. But with `<userCurrentTimestamp>true`, you build a new, different image each time with `jib:build` or `jib:dockerBuild`.
