### ISSUE TITLE
Refactor WAR vs. JAR processing with more OO style

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#1584]
In classes like `<Plugin>ProjectProperties` and `PluginConfigurationProcessor`, there is a lot of branching using `isWarProject()` checks to determine how to build the project. Instead, it may be cleaner to have different objects with a common interface for JAR vs. WAR projects to handle the separate code paths.

**Comment by mcabezas** [comment]
Is this tech debt open to be contributed?

**Comment by chanseokoh** [comment]
Thanks for looking into the issue. But the code around `ProjectProperties` and `isWarProject()` has been changed a bit after this issue is open, and I think there will be more changes regarding packaged WAR containerization. After that, we need to evaluate if this issue still stands.

I think #1727 is a more suitable first-time issue with a simple fix.

**Comment by JoeWang1127** [comment]
close as not planned
