### ISSUE TITLE
Enable to not split resources and classes

### ISSUE THREAD

**Issue by rmannibucau** [GoogleContainerTools/jib#1713]
Hi guys,

CDI uses beans.xml to mark a jar or folder as a module - I simplify a bit but this is what is broken for me.
Since JIB split resources and classes in two folder, the module is split and therefore the resources module is discovered correctly but not the classes one so the application is broken.

Is it possible to get an option to keep both merged - I'm using the maven plugin if important?

Thanks,
Romain

**Comment by loosebazooka** [comment]
Yeah this is a known issue. https://github.com/GoogleContainerTools/jib/issues/1488, not sure what we want to do about it yet.

**Comment by chanseokoh** [comment]
As discussed in https://github.com/GoogleContainerTools/jib/issues/1488#issuecomment-465452816, I think this can be best resolved when we support (#905), which is really about embedding a single JAR instead of the current behavior that we put individual class files and resources into separate directories. The downside could be that, you no longer have separate layers for classes and resources and hence lose some degree of granularity, but this seems a good-enough solution.

I will close this, as this looks like a dup of #1488. You can follow up in #1488, but if you think there's something different worth another issue, feel free to re-open and update.

**Comment by chanseokoh** [comment]
#905 is fixed, and the next Jib release will enable embedding a JAR. Using a JAR, since the class files and resource files will be loaded from the same location, I believe it will resolve this issue.

**Comment by TadCordle** [comment]
v1.4.0 has been released with the JAR support @chanseokoh mentioned!
