### ISSUE TITLE
Support for docker buildArgs

### ISSUE THREAD

**Issue by neoword** [GoogleContainerTools/jib#1806]
- Docker supports concept of [build time variables](https://docs.docker.com/engine/reference/commandline/build/) through the use of `--build-arg`.
- Typically these args are used on base images to parameterize them at build-time (e.g. java-version for base image)

Is there a way to support `--build-arg` in jib?

**Expected behavior**:
Would like to see some config in the `<container>` section

```
...
<build-args>
  <arg1>value1</arg1>
  <arg2>value2</arg2>
</build-args>
...
```
-OR- an equivalent workaround, will see if ENV works.

**Comment by briandealwis** [comment]
Jib is run at build time and it is configurable from the pom/build.script, and many of those values can be overridden by system properties specified on the command-line. If you want to change the JDK, for example, then change the `<from><image>` to specify an alternative base image. Or change the entrypoint, maybe using a maven property, to select from multiple JDKs un tour image.

**Comment by neoword** [comment]
Changing the JDK was just "an example".  This is more a parity-request with existing images built from Dockerfile that leverage `--build-arg` vs env vars (which jib happily supports).

**Comment by loosebazooka** [comment]
Does docker persist `--build-arg` in a built image? Can you provide an example of how you are using this?

**Comment by chanseokoh** [comment]
> Clearly a workaround is to build a "shim"/interim layer with the appropriate `--build-arg` and use that

`--build-arg` is a build-time arg (as you said), which is available and effective only at build time within the scope of `Dockerfile`. I don't think a built image has place to persist such build-time info. Also, I believe `--build-arg` is Docker client-specific, so it doesn't really make sense that such info is saved into a container image.

**Comment by neoword** [comment]
> _it doesn't really make sense such info is saved into a container image_

Thanks @chanseokoh. Working with internal folks to clarify. Please stay tuned.

**Comment by awittha** [comment]
`--buildArg` is provided to the `docker build` command, e.g.

`docker build --buildArg APP_NAME=my-app-name`.

It will correspond to a directive in the `Dockerfile` being used, e.g.

`Dockerfile`:
```
...

ARG APP_NAME

RUN mkdir /usr/local/${APP_NAME}
...
```

Does `jib` support providing the Build Arg to such a Dockerfile? If not, such Dockerfiles cannot be built with `jib`.

**Comment by awittha** [comment]
To clarify:

A base image used as `jib`'s `FROM` may have contained [`ONBUILD`](https://docs.docker.com/engine/reference/builder/#onbuild) directives in its `Dockerfile`.

If the base image contained `ONBUILD ARG ...`, then, `jib` needs a way to provide a Build Arg at build time, or else the built image will not be correct.

Consider

*Base Image* `Dockerfile`:

```
FROM ubuntu

ONBUILD ARG APP_JAR
ONBUILD ARG APP_DIR
ONBUILD RUN curl https://search.maven.org/remotecontent?filepath=${APP_JAR} > ${APP_DIR}/app.jar
```

To build an image for a project with jib, using such a Docker image as the parent image, the `APP_JAR` and `APP_DIR` build args must be provided, or else the image won't be able to be built properly.

It may be (it looks like, from what I see), that `jib` also does not support `ONBUILD` directives in base images.

**Comment by neoword** [comment]
Perhaps title of this issue is wrong?
Title rename:
_jib honors `ONBUILD` triggers in `FROM` image_

@awittha I have typically found `--buildArg` used in `ONBUILD` directives (from the base image) and indeed that is what I am dealing with in my use case.

See https://docs.docker.com/engine/reference/builder/#onbuild (as referenced in previous comment)

**Comment by chanseokoh** [comment]
Ah, the `ONBUILD` directive. Now I see the use case.

Looks like `ONBUILD` is a Dockerfile-specific extension that [does not conform to OCI](https://github.com/opencontainers/image-spec/blob/master/config.md). `ONBOARD` and `ARG` are meaningful and effective only within a `Dockerfile` at build time when building with the Docker CLI.

Now, `ONBUILD` is a very interesting one; everything specified by `ONBUILD` is to be executed inside another `Dockerfile` build later, when the image built with `ONBUILD` is used in `FROM`. For example, if I build an image with `ONBUILD`, the image configuration has

```java
            "Entrypoint": null,
            "OnBuild": [
                "ARG APP_DIR",
                "RUN curl https://search.maven.org/remotecontent?filepath=com/google/cloud/tools/jib-core/0.10.0/jib-core-0.10.0.jar > ${APP_DIR}/jib-core-0.10.0.jar"
            ],
            "Labels": null
        },
 ```

Then, if this image is used in `FROM` in another `Dockerfile`, the Docker CLI will read in this information and actually execute them as-is while building.

**Comment by briandealwis** [comment]
I'd be interested in why you need to use `ONBUILD` in your builds, as downloading from Maven Central seems something that Maven and Gradle already handle pretty well :-)

**Comment by chanseokoh** [comment]
@awittha @neoword the way Jib builds an image is fundamentally different from how the Docker CLI builds an image using `Dockerfile` (reproducible vs. non-reproducible, declarative vs. imperative, Docker and Dockerfile-less build vs. requiring Docker deamon and client, require root-privilege vs. not). Jib is in a very different realm, so unfortunately, it is very difficult to support `ONBUILD` unless we radically change our opinionated philosophy in build an image should be built. Basically, we don't "run" Dockerfile directives, particularly the ones like `RUN` that executes something. Jib doesn't provide/include a Docker runtime (that is one of the points of Jib).

**Comment by neoword** [comment]
@chanseokoh Makes sense.
> Jib is in a very different realm... unless we radically change our opinionated philosophy

So for "reproducibility" make an "interim" `<FROM>` image.

@awittha you agree?

**Comment by awittha** [comment]
@neoword:

If `jib` ideologically won't support building `FROM` an image that has `ONBUILD` triggers, then you'd have to use `docker build` to build an interim image with the correct args provided.

Unfortunately, if `jib` can't do this, you'd have to keep some tool that can use the `docker` client in your build process in order to use such parent images.

@chanseokoh:

It's not about Java or Maven Central, specifically - I just chose those as simple examples for the pseudocode. It's about the _pattern_ of building & distributing templatized/parameterized base images where the distributor knows what consumers will want to do, but not necessarily what they'll want to do it _to_.

A more-complex example might be an image that would run a Java servlet in a Jetty servlet container. An organization might decide to abstract the mechanics of installing & configuring a servlet container, an OS, and a java runtime away from the authors of servlet-based webapps. To achieve this, they might distribute a base image with ONBUILD ARGs for `JETTY_VERSION`, `JAVA_VERSION`, `WEBAPP_WAR_COORDS`.  The webapp authors now have only coarse controls over parts that the base image maintainers specifically identified as worth exposing downstream.

In this case it's impractical to pre-build every possible combination of (java version) + (jetty version) + base OS version, to preserve the time-savings of pre-installing things for downstream consumers.

This is (at least in my part of the world) a common pattern.

Without support for `ONBUILD` and `ARG` in `jib`, these webapp authors cannot use such a base image.

It sounds like `jib`'s thought about this and decided "one shouldn't do such things with base images." Unfortunately, that means applications in ecosystems like the above can't just try `jib` instead of their existing docker tooling - they'll have to refactor their whole upstream base image hierarchy, too.

**Comment by neoword** [comment]
I'm going to close this. Thanks @chanseokoh.
