### ISSUE TITLE
jib in multi-project-build

### ISSUE THREAD

**Issue by Docjones** [GoogleContainerTools/jib#1891]
**Environment**:

- *Jib version:* 1.4.0
- *Build tool:* gradle 5.1

**Description of the issue**:
We have a multi-project gradle built which builds one WAR file and multiple JAR. I am struggling with the fact, that due to the configured WAR plugin, jibExplodedWar seems to be triggered for the JAR subprojects. 

e.g.
```
apply plugin 'war'
...
project ( ':sub1 ){

   jib {
     from {
       image = 'openjdk:8-jre-alpine'
     }
     to {
       image = "${idsDockerRepoURL}/${project.group}.${project.name}".toLowerCase()
       auth {
          ....
       }      
       tags = ["${project.version}".toString(), "latest"]
     }
     container {
       mainClass = '...'
       jvmFlags=['-Xms256m','-Xmx512m']
       useCurrentTimestamp = true
     }
   }
    
   jar {
        baseName = project.name
        archiveName = "sub1.jar"
        from ("${projectDir}/../....") {
            into "...."
        }
    }
}
```

Is there a possibility to deactivate the jibExplodedWar-Task and revert back to the jar-file jib-build?

regards
Marc

**Comment by loosebazooka** [comment]
if you do not apply the `war` plugin on a subproject it wont be triggered.

**Comment by Docjones** [comment]
Problem is - the main project and several subprojects needs the war plugin. I am not very skilled in gradle and dont know how to remove the plugin from the subproject block. 

Do you have a hint for me?

thanks & regards
Marc

**Comment by loosebazooka** [comment]
applying the 'war' plugin on the parent shouldn't apply it to the subprojects so your first line is okay. You just need to selectively apply war to the subprojects correctly

so you can:
1. move the `apply plugin "war"` directly into the build.gradle file for the subproject instead of doing everything in the parent build.gradle
2. filter your projects somehow perhaps using the solutions in here: https://stackoverflow.com/questions/13868177/apply-configuration-to-specific-projects-in-gradle-build-script

**Comment by Docjones** [comment]
Yeah - i found that out the very second: applying in the main project and only those sub-projects that need the war plugin selectively.

Thanks thousand times!
