### ISSUE TITLE
Add the tags to the manifest.json

### ISSUE THREAD

**Issue by DavyLandman** [GoogleContainerTools/jib#2043]
**Environment**:

- *Jib version:* 1.6.0
- *Build tool:* maven 3.6.0
- *OS:* Windows 10

**Description of the issue**:
The `<tags>` feature (specify multiple tags for the image) does not work for `buildTar`, as the `manifest.json` only contains `"repoTags": [ "image:latest"]`. It would be very useful to push the tags to this metadata. 

I think I could add it to the library, but first, is this desirable? To have all the tags in the tar? Currently it is done as an upload of the image and then tagging it multiple times (or uploading it multiple times with different tags for remote repositories). I think it does, so that the tar is self-contained.

**Expected behavior**:

When you define multiple tags, they end up in the tar, not as extra calls to the docker client/docker registry.

**Steps to reproduce**:

  1. on a random project `mvn clean compile jib:buildTar -Djib.to.tags=extr`
  2. open the `jib-image.tar/manifest.json` and see it only contains the  ":latest" tag

**Comment by TadCordle** [comment]
Good idea, I think we can add this. If we add the additional tags to `repoTags`, this also lets us avoid the extra `docker tag` calls we currently do in `jibDockerBuild`. However I think the logic for building to the registry will need to stay the same, since I don't think that uses a tar.

>I think I could add it to the library, but first, is this desirable?

Feel free to take a stab at it if you have the time! If not, it's no problem, I actually just ended up doing a lot of the necessary work to see if this issue made sense :smile:

**Comment by DavyLandman** [comment]
thanks, looked at the PR, it was similar to how I solved it, I just got stuck without a grc account, so couldn't run the integration tests.

**Comment by TadCordle** [comment]
@DavyLandman 1.7.0 has been released with this fix!

**Comment by DavyLandman** [comment]
great, thanks :)
