### ISSUE TITLE
1.7.0 noticeably slower than 1.6

### ISSUE THREAD

**Issue by spazbob** [GoogleContainerTools/jib#2094]
**Environment**:

- *Jib version:* 1.7.0
- *Build tool:* Maven 3.6.1 (embedded in Eclipse 4.13, running on AdoptOpenJDK 13+33)
- *OS:* Windows 10

**Description of the issue**:
I have noticed a roughly 30% increase in the length of time building an image takes with 1.7.0 vs 1.6.x versions.

The delay seems to occur between these two log lines:

[INFO] Retrieving registry credentials for registry-1.docker.io...
and
[INFO] Using base image with digest: sha256:b2cb057d533ccf5b646e112184b00bb64c05b12535acf2bb5d30b7c08bed6c7c

**Expected behavior**:
No degradation in build time

**Steps to reproduce**:

  1. Build image with 1.6.1
  2. Change JIB plugin conf to use 1.7.0
  3. Build image and compare times

**`jib-maven-plugin` Configuration**: 
```xml
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>1.7.0</version>
				<configuration>
					<from>
						<image>adoptopenjdk/openjdk13:debian-slim</image>
						<auth>
							<username>[removed]</username>
							<password>[removed]</password>
						</auth>
					</from>
					<to>
						<image>${docker.repository}/${project.artifactId}</image>
						<auth>
							<username>[removed]</username>
							<password>[removed]</password>
						</auth>
					</to>
					<extraDirectories>
						<paths>
							<path>../ecv-devops/monitoring/jib/</path>
						</paths>
					</extraDirectories>
					<allowInsecureRegistries>true</allowInsecureRegistries>
					<container>
						<jvmFlags>
							<jvmFlag>-javaagent:/appdynamics/AppServerAgent/javaagent.jar</jvmFlag>
							<jvmFlag>-XX:+HeapDumpOnOutOfMemoryError</jvmFlag>
							<jvmFlag>-Djava.security.egd=file:/dev/./urandom</jvmFlag>
						</jvmFlags>
						<creationTime>USE_CURRENT_TIMESTAMP</creationTime>
					</container>
				</configuration>
			</plugin>

```

**Log output**: 
[INFO] --- jib-maven-plugin:1.7.0:build (default-cli) @ ecv-webapp ---
[WARNING] Authentication over HTTP is enabled. It is strongly recommended that you do not enable this on a public network!
[WARNING] Setting image creation time to current time; your image may not be reproducible.
[INFO] 
[INFO] Containerizing application to [removed]/ecv-webapp...
[WARNING] Base image 'adoptopenjdk/openjdk13:debian-slim' does not use a specific image digest - build may not be reproducible
[INFO] Retrieving registry credentials for [removed]...
[INFO] Getting manifest for base image adoptopenjdk/openjdk13:debian-slim...
[INFO] Building dependencies layer...
[INFO] Building resources layer...
[INFO] Building classes layer...
[INFO] Building extra files layer...
[INFO] The base image requires auth. Trying again for adoptopenjdk/openjdk13:debian-slim...
[INFO] Retrieving registry credentials for registry-1.docker.io...
[INFO] Using base image with digest: sha256:b2cb057d533ccf5b646e112184b00bb64c05b12535acf2bb5d30b7c08bed6c7c
[INFO] 
[INFO] Container entrypoint set to [java, -javaagent:/appdynamics/AppServerAgent/javaagent.jar, -XX:+HeapDumpOnOutOfMemoryError, -Djava.security.egd=file:/dev/./urandom, -cp, /app/resources:/app/classes:/app/libs/*, [removed]]
[INFO] 
[INFO] Built and pushed image as [removed]

**Additional Information**: 

Looking for advice initially on what debugging can be turned on to try and identify which part of the process is slower. I can see in 1.7.0 there were a number of changes in how images were produced so suspect something in my environment is creating a slow down in relation to this.

The repository I am pushing to is remote (AWS EC2 instance).

**Comment by chanseokoh** [comment]
Thanks for the report. We will look into it.

For the JDK 13 issue, you are right. You can manually set the main class for < 1.7.0 to circumvent the problem: https://github.com/GoogleContainerTools/jib/issues/2015#issuecomment-534168864 This should allow you to compare the time with 1.6.x.

**Comment by briandealwis** [comment]
Comparing Jib 1.6.1 vs 1.7.0 with `buildTar` on the same project with class files already built with `mvn package` reveals no noticeable difference. 

You may be seeing differences due to network traffic.  Please ensure you're using the same base image as `docker images` reports that `adoptopenjdk/openjdk13:debian-slim` is 397MB which is considerably larger than `distroless/java:11`'s 195MB.

<details>
<summary>timing comparisons of 1.6.1 vs 1.7.0 `buildTar`</summary>

Method: run `buildTar` on pre-built Maven project 5 times.  Measure wall-clock time reported by `time`:

```
rm target/jib-image.*; time mvn com.google.cloud.tools:jib-maven-plugin:1.6.1:buildTar
```

|Attempt|1.6.1|1.7.0|
| :---- | :---- | :---- |
|1 | 2.890 | 3.733 |
| 2 | 3.162 | 3.075 |
| 3 | 3.192 | 2.838 |
| 4 | 2.911 | 2.888 |
| 5 | 2.764 | 2.809 |
| **Average** | 2.98 | 3.069 |

</details>

**Comment by chanseokoh** [comment]
Yeah, I also tried 1.6.0 vs 1.7.0 with GCR (gcr.io) that gives consistent and reliable speed but haven't noticed difference. I get very consistent results for both. Anyways, you can pass `-X` to Maven to see Jib's rough timing logs on various operations.

Unrelated, since you said the registry is a remote one on AWS EC2, I discourage using `<allowInsecureRegistries>` if the network traffic goes through the Internet. Especially if you have to use `-Djib.sendCredentialsOverHttp`, that means you are talking to the registry over plain HTTP, and it is extremely easy for anyone in the wild to see your username and password.

**Comment by raizoor** [comment]
I have compared the times between these versions, using maven 3.6 and openjdk11, using my internal registry (harbor - https) and can't see these slowness problem too.
I'm using mvn compile jib:build.

**Comment by spazbob** [comment]
@chanseokoh Thanks, I'll try with the `-X` flag in Maven to see if more specifics help on timings.

It does feel like the remote registry is doing some extra work potentially; I can see that network utilisation is pegged at 100% for the extended period Jib seems to be taking. It almost feels like more data is being uploaded to the server than used to be but I'll do some testing to figure it out. Possibly if others are testing locally this isn't showing up as there wouldn't be any data transfer overhead.

**Comment by chanseokoh** [comment]
@spazbob have you found anything yet?

**Comment by chanseokoh** [comment]
I'll close this for the moment, but if you find any lead, just reopen and update. Thanks!
