### ISSUE TITLE
Jib built image does not show label, env, layers information in Docker manifest(Quay.io)

### ISSUE THREAD

**Issue by caiwei-ebay** [GoogleContainerTools/jib#2168]
Jib Core : 0.12.0
We built an image with Jib core and pushed the image to Quay.io.

We've added labels, ENVs & a few file copies to the image, however the manifest in Quay does not show the ENVs, labels and layer information, instead we've got layers like "jib-core 0.12"...

<img width="1160" alt="Screen Shot 2019-11-21 at 3 09 29 PM" src="https://user-images.githubusercontent.com/7812711/69315390-5aa7b700-0c71-11ea-9d40-152cf88026b4.png">

Here is the source code:
Jib.from(RegistryImage.named(baseImage).addCredential("...","..."))
                    .addLabel("git.url", "test.git.url")
                    .addLabel("git.branch", "test.git.branch")
                    .addEnvironmentVariable("BASE_IMAGE", "test.base.image")
                    .addLayer（... jars ...,  "/app/lib")
                    .addLayer(...classes..., "/app/classes")                   .containerize(Containerizer.to(RegistryImage.named(targetImage).addCredential("...","..."));

**Comment by chanseokoh** [comment]
Hi @caiwei-ebay,

After I've played a bit with the Quay UI, I became confident that the labels and environment variables are correctly added into the image built by Jib Core. You will be able to verify this by

```
$ docker pull <your image>
$ docker inspect <your image>  | jq -r '.[].Config.Env'
$ docker inspect <your image>  | jq -r '.[].Config.Labels'
```
(or just `docker inspect <your image>` if you don't have `jq`.)

It seems that the Quay UI is tailored heavily toward images built by the Docker CLI. The UI just seems to examine history values and if they are of specific format Docker generates, it tries to parse and show them in the UI. For example, the history of my image looks like this:

```
$ docker history quay.io/francium25/test:latest 
IMAGE               CREATED             CREATED BY                                     SIZE                COMMENT
82032c1caf5e        18 minutes ago      /bin/sh -c #(nop)  LABEL my.label=is.awesome   0B                  
4e3712b05af8        18 minutes ago      /bin/sh -c #(nop)  ENV cool.env=value          0B                  
e8f8511bcd2e        49 years ago        bazel build ...                                106MB               
<missing>           49 years ago        bazel build ...                                1.93MB              
<missing>           49 years ago        bazel build ...                                15.1MB              
<missing>           49 years ago        bazel build ...                                1.82MB   
```

and while my image contains many more env variables,

```
chanseok$ docker inspect quay.io/francium25/test | jq -r '.[].Config.Env'           
[                                                  
  "JAVA_VERSION=8u232",                            
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",                                
  "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt",                                                 
  "cool.env=value"                                 
]                                                  
```

the Quay UI shows only `my.label` and `cool.env`.

![quay_ui](https://user-images.githubusercontent.com/10523105/69356316-4c49a300-0c51-11ea-8852-f3ff96c587fa.png)

And actually the Quay "Manifest Layers" UI is misleading, because the `ENV` and `LABEL` shown in the image above are not layers. My image has 4 layers, but the UI makes you think it has 6 layers.

So, the Quay UI is trying their best to show some useful history information, and it works for images built from a `Dockerfile`. But obviously, this won't work with images built by other tools, including Jib. And I don't really think Jib should try to mimic the history string that the Docker CLI generates.

**Comment by chanseokoh** [comment]
I'll close this as a non-issue. My sample image in the screenshot above isn't even built with Jib. It was built with `Dockerfile` based on a public [Distroless](https://github.com/GoogleContainerTools/distroless). The base image built by Bazel, as you can check in the screenshot. However, feel free to update if you have any feedback.

**Comment by caiwei-ebay** [comment]
Thanks for your reply. Docker inspect is do having all information. I'm just curious why Docker Hub or Quay.io cannot show the detailed information in manifest as Docker CLI packaged images. Thanks for your explanation and now I know why. Although this is a slight issue, however the user experience would be much better if Jib can bake the history string to the image.
