### ISSUE TITLE
Loading custom root CA into /etc/ssl/certs/java/cacerts

### ISSUE THREAD

**Issue by rameshvenk** [GoogleContainerTools/jib#2240]
**Environment**:

- *Jib version:* 1.8.0
- *Build tool:* Apache Maven 3.6.2
- *OS:* MacOS

**Description of the issue**:
The /etc/ssl/certs/java/cacerts file contains root CA certs. Since I have an internal CA that is used for self signed certs, I would like to load the internal root CA certs into the system keystore

**Expected behavior**:
During the container build process, please provide a way to provide custom certs, or a custom cacerts file to override the /etc/ssl/certs/java/cacerts file

**Steps to reproduce**:

  1. Build image with the default gcr.io java8 container image using Spring Boot
  2. Attempt to access a site with self signed certs
  3. An exception is thrown indicating the certs are untrusted

**Comment by chanseokoh** [comment]
Hi @rameshvenk,

> I would like to load the internal root CA certs into the system keystore

Just to make sure, because the term "keystore" raises some confusion. I believe you mean "system truststore"?

IMO, I think this is out of the scope of Jib. Have you tried these JVM parameters?

* `-Djavax.net.ssl.trustStore`: specifies the truststore file to use to validate client certificates.
* `-Djavax.net.ssl.trustStorePassword`: specifies the passphrase to access the truststore file.

AFAIK, you should a truststore file that includes all the usual root CA certs in addition to your custom certs.

Note there are `-Djavax.net.ssl.keyStore` and `-Djavax.net.ssl.keyStorePassword` counterparts.

**Comment by rameshvenk** [comment]
Yes, I meant system truststore. My apologies for the confusion.

If I use the `-Djavax.net.ssl.trustStore` parameters, would that mean that I have mount a volume and copy the custom trust store as a part of my deployment?

**Comment by chanseokoh** [comment]
I actually think that (i.e., providing the truststore dynamically at runtime) can be one of the options. Maybe a suitable one considering the nature of the file.

However, if you want to embed the truststore file at compile-time no matter what, you can directly put the file into the container using the `<extraDirectories>` feature. Actually, if you put your cacerts file at `<project root>/src/main/jib/etc/ssl/certs/java/cacerts`, Jib will copy and placed it at `/etc/ssl/certs/java/cacerts` in the image (i.e, overwriting it). I initially assumed wrongly you were talking about cacerts for Jib runs, but now I get that the cacerts is for the application inside the image. You may place the file somewhere else and use `-Djavax.net.ssl.trustStore`, but maybe just overwriting `/etc/ssl/certs/java/cacerts` is simpler.

**Comment by rameshvenk** [comment]
Thank you! I think your suggestion to put it under “src/main/jib” should work very well. My apologies if I wasn’t more clear earlier.
