### ISSUE TITLE
Set folder permission

### ISSUE THREAD

**Issue by tamtakoe** [GoogleContainerTools/jib#2249]
There is no way to set permissions for folder (e.g. chmod -R 777 /opt/app). Permissions work just for files.
There is also no way to run sh-command (Build it in base image is total overhead).
Think, please, this functionality

**Comment by chanseokoh** [comment]
Hi @tamtakoe,

(I assume you set `jib.appRoot` to `/opt/app`.) Files and directories under `/opt/app` will already be world-readable and executable. In almost all cases, this is sufficient and actually the right permissions to have. By wanting to do `chmod -R 777`, I assume you want to either modify your application files or create new files under `/opt/app` while your application is running. One of the best container-building practices is to make your application immutable:

https://cloud.google.com/solutions/best-practices-for-operating-containers#immutability

If you are allowing your application to dynamically mutate itself at runtime, that is often a sign that there is a better way to achieve your ultimate goal. (For example, if your application needs to create a temporary file, it should use a tmpfs and not write into the application directory.) We'd like to be a responsible steward in the community to help people build images correctly and securely, so we are a bit reluctant to open the exploitable path where people may inadvertently make their applications mutable; after all, Jib builds images in an opinionated way by applying container best practices. In fact, by preventing modifying `/opt/app`, perhaps we've already given you the potential opportunity to review your application to understand why the directory and files need to be mutable on production.

But we are very open to discussions and feedback. If there is a legitimate use-case to justify lifting the best practice, we may open the door to this feature. Could you explain in details why you want to set the 777 permissions for your application?

**Comment by tamtakoe** [comment]
Hi @chanseokoh!
Yes `/opt/app` is my appRoot. Thank you for great answer! I'm totally agree with you! My idea why I need this is too simple - because I try to dockerize old project which uses app directory for something... I don't know for what and I have no desire to investigate it. I hope this project will be rewritten this year but I need dockerize it anyway :-)

I understand that run-command is risky way, but sometime it needs for dockerize some legacy code or easy migration from other plugins. E.g. what we had with spotify plugin
```
<runs>
  <run>sh /opt/scripts/unpack.sh</run>
  <run>mkdir -p /var/log/projectfolder</run>
  <run>mkdir -p /opt/projectfolder/data/berklydb</run>
  <run>chmod -R 777 /opt/app</run>
  <run>chmod -R 777 /var/log/projectfolder</run>
</runs> 
```
You can open this feature and set it deprecated and write something scary in console

**Comment by chanseokoh** [comment]
Although I don't recommend, there's a hacky way to set arbitrary permissions to existing and non-existing directories (including `<appRoot>`) using the `<extraDirectories>` feature: https://github.com/GoogleContainerTools/jib/issues/1257#issuecomment-440857113 This works whether or not the directories exist in the image; directories will be created if they don't exist. However, you cannot modify permissions of existing files using this trick, unless you provide a new file with `<extraDirectories>` and overwrite an existing one. (They way `<extraDirectories>` work is simply copying files and directories into the image.) Also, permissions in `<extraDirectories>` aren't recursively applied to subdirectories, so you'll have to list all directories for which you want to set permissions. it is not possible to change permissions of existing files

Also, in order for this hack to work, the leaf directory must not be a symlink. For example, if `/var/log/projectfolder` is a symlink (which isn't in your case) pointing to `/var/log/another`, you should use `/var/log/another` in `<extraDirectories>`.

And as for running arbitrary commands, unfortunately this is largely incompatible with the mode Jib operates in, because the way Jib builds an image is fundamentally different from how Docker does: https://github.com/GoogleContainerTools/jib/issues/1806#issuecomment-505526975 We build images in a declarative and reproducible way without actually requiring to have a runtime component to be able to run an image at image build-time; running an image basically destroys reproducibility. So unfortunately it is very difficult for Jib to support "running" arbitrary commands at image building-time.

**Comment by chanseokoh** [comment]
Re: setting permissions, if you are really in a situation like you described (having less-secure legacy code that you cannot update), then perhaps writing a [Jib extension](https://github.com/GoogleContainerTools/jib-extensions) may be the best option for you. This should be a better way than the hack I mentioned in https://github.com/GoogleContainerTools/jib/issues/2249#issuecomment-578937936.

**Comment by chanseokoh** [comment]
I believe the comments above as well as #1257 provide enough answers and potential solutions to this issue.
