### ISSUE TITLE
 jib-maven-plugin fails if maven-war-plugin "warName" property references maven property created by properties-maven-plugin

### ISSUE THREAD

**Issue by michaelze** [GoogleContainerTools/jib#2577]
**Environment**:

- *Jib version:* 2.4.0
- *Build tool:* Maven 3.6.0
- *OS:* Ubuntu (WSL)

**Description of the issue**:
This issue further extends #2206. I.e. using the `<warName>` property of the maven-war-plugin works as expected in combination with the jib-maven-plugin. Even using a maven property for the `<warName>` works fine, as long as the maven property is defined somewhere in the pom itself.
In our build however, we are using the plugin `org.kuali.maven.plugins:properties-maven-plugin:2.0.1` to be able to define certain properties that are used throughout the project in one place. This is where the jib-maven-plugin starts to complain about not being able to find the .war file. The error message reads as follows: 

`[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.4.0:build (default) on project helloworld.ui.html.app.war: Obtaining project build output files failed; make sure you have compiled your project before trying to build the image. (Did you accidentally run "mvn clean jib:build" instead of "mvn clean compile jib:build"?): /path/to/src/jib-test-repository/helloworld.ui.html.app.war/target/${ui.html.war.name}.war -> [Help 1]`

It seems to me as if the `<warName>` property was read and all properties it contains were resolved against the maven properties that are defined at that time. The properties-maven-plugin seems to inject its properties _later_ which causes them to not be taken into account by the jib-maven-plugin.

**Expected behavior**:
Building a `war` module with the jib-maven-plugin should work, even if the `<warName>` property of the `maven-war-plugin` contains a maven property that is defined by the `properties-maven-plugin`.

**Steps to reproduce**:
I updated the code from the #2206 issue to demonstrate this problem: https://github.com/michaelze/jib-test-repository

Working configuration (initial repository 

1. Alter the pom.xml File in helloworld.ui.html.app.war and change the target image to a location you can push to.
1. Execute the build as follows: mvn -Djib.to.auth.username=xxxxx -Djib.to.auth.password=xxxxx -DskipTests -P docker clean package (Success)

Error when using property defined by `properties-maven-plugin` for `<warName>`

1. Change the configuration of the `maven-war-plugin` in the `helloworld.ui.html.app.war/pom.xml` (comment out the `<warName>` property with the literal value and remove the comments from the `<warName>` property containing the maven property reference
1. Execute build like mentioned above

**`jib-maven-plugin` Configuration**: 
```xml
<!-- from parent module (build / pluginManagement -->
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>jib-maven-plugin</artifactId>
	<version>2.4.0</version>
	<executions>
		<execution>
			<phase>package</phase>
			<goals>
				<goal>build</goal>
			</goals>
		</execution>
	</executions>
</plugin>

<!-- from module configuration -->
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>jib-maven-plugin</artifactId>
	<configuration>
		<from>
			<image>tomcat:9-jdk11</image>
		</from>
		<to>
			<image>changeme/testimage</image>
		</to>
	</configuration>
</plugin>
```

**Comment by chanseokoh** [comment]
Thanks for the detailed info and the sample project. I think I understand what's going on, but I don't find a good way to make this work.

`properties-maven-plugin` has certain inherent limitations due to the fact that it runs as an additional plugin during Maven execution, which means that the property injection happens far after Maven has already parsed `pom.xml` and completed certain evaluation steps. For example, [you can't use the plugin to substitute a dependency version](https://stackoverflow.com/questions/14725197/reading-properties-file-from-pom-file-in-maven/14727072#14727072). The SO answer goes into explaining at high level some stages Maven goes through (whose details I honestly don't fully understand), but the point is that it's inevitable that `properties-maven-plugin` has certain limitations.

In your case, if I check the effective POMs, I see that `<warName>` remains untouched.
```
$ mvn -DskipTests -pl helloworld.ui.html.app.war -am package help:effective-pom | grep war\.name
      <ui.html.war.name>uihtml</ui.html.war.name>
      <ui.html.war.name>uihtml</ui.html.war.name>
      <ui.html.war.name>uihtml</ui.html.war.name>
      <ui.html.war.name>uihtml</ui.html.war.name>
      <ui.html.war.name>uihtml</ui.html.war.name>
              <warName>${ui.html.war.name}</warName>
                <warName>${ui.html.war.name}</warName>
            <warName>${ui.html.war.name}</warName>
```

OTOH, if you pass the corresponding system variable on the command line, or directly set the property inside the project `pom.xml` (as you tried), then I see the effective POM already substituted the given value for `<warName>`.

```
$ mvn -DskipTests -Dui.html.war.name=cool.war.name -pl helloworld.ui.html.app.war -am package help:effective-pom | grep war\.name
[INFO] Building war: /home/chanseok/tmp/gitrepos/jib-test-repository/helloworld.ui.html.app.war/target/cool.war.name.war
      <ui.html.war.name>uihtml</ui.html.war.name>
      <ui.html.war.name>uihtml</ui.html.war.name>
      <ui.html.war.name>uihtml</ui.html.war.name>
      <ui.html.war.name>uihtml</ui.html.war.name>
      <ui.html.war.name>uihtml</ui.html.war.name>
              <warName>cool.war.name</warName>
                <warName>cool.war.name</warName>
            <warName>cool.war.name</warName>
```

```
$ mvn -DskipTests -pl helloworld.ui.html.app.war -am package help:effective-pom | grep war\.name
[INFO] Building war: /home/chanseok/tmp/gitrepos/jib-test-repository/helloworld.ui.html.app.war/target/inlined.war.name.in.pom.xml.war
      <ui.html.war.name>uihtml</ui.html.war.name>
      <ui.html.war.name>uihtml</ui.html.war.name>
      <ui.html.war.name>uihtml</ui.html.war.name>
      <ui.html.war.name>uihtml</ui.html.war.name>
      <ui.html.war.name>uihtml</ui.html.war.name>
              <warName>inlined.war.name.in.pom.xml</warName>
                <warName>inlined.war.name.in.pom.xml</warName>
            <warName>inlined.war.name.in.pom.xml</warName>
```

The problem is that, in Maven, the only way I am aware of for one Maven plugin (`jib-maven-plugin`) to read a config value of another plugin (`maven-war-plugin`) is through the final effective POM model that Maven evaluated. Maven is probably instantiating plugin configuration instances while factoring in session properties, so I guess that's the reason why each plugin fortunately gets the substituted values in their config MOJO. However, for one plugin to consult a config value of another plugin, AFAIK, the final POM model is the only medium, and the model just contains the placeholder values.

Unless there's another way that I'm unaware of to get the evaluated values of another plugin, I think this is somewhat tricky to make it work. Theoretically Jib could implement an independent evaluation logic to resolve `${..}` expressions in a string value using the Maven session/system properties, but I don't really feel this is what Jib should do.

**Comment by michaelze** [comment]
@chanseokoh 
Thank you for your analysis, from the behavior I was seeing, I kinda expected something along those lines.

What I don't get though is why the maven-war-plugin works with the property set by the properties-maven-plugin (i.e. why the created .war file has the name I defined in my .properties file).
I looked at the code of the maven-war-plugin (https://github.com/apache/maven-war-plugin/blob/master/src/main/java/org/apache/maven/plugins/war/WarMojo.java) to maybe find a "standard" way to also implement the same behavior in the jib-maven-plugin but I could not find any custom/non-custom code to "parse a string and replace property references from the maven session". Somehow, Maven seems to set the warName property already parsed and replaced as soon as the WarMojo is constructed/initialized.
There's also a difference in those two cases:

- maven-war-plugin: the `${property}` reference in the `<warName>` property of the war plugin's configuration seems to be parsed and replaced soon enough for the plugins execution to be correct
- jib-maven-plugin: it is not some value of the plugins' configuration itself that needs to be parsed and replaced but the value of another plugins configuration value. In your implementation, you are reading the value from the parsed Dom whereas actually you are interested in the value the plugin is using at runtime.

So maybe it would be possible to not parse the value from the war plugin's Dom but to get the value from its Mojo at runtime?

I agree with you, that implementing the parsing of the warName string and doing a replacement using properties from the maven session is not something one would expect the jib-maven-plugin to do, although, I was wondering if there might be a standard way of accomplishing this (a quick google search did not support this assumption, though).

**Comment by chanseokoh** [comment]
> What I don't get though is why the maven-war-plugin works with the property set by the properties-maven-plugin (i.e. why the created.

No wonder. Not just `maven-war-plugin`, but `jib-maven-plugin` also works with `properties-maven-plugin` for _its `<configuration>` values_. (For example, `<configuration><to><image>`.) Hence the following guess in my previous comment:

> Maven is probably instantiating plugin configuration instances while factoring in session properties, so I guess that's the reason why each plugin fortunately gets the substituted values in their config MOJO.

Therefore, the problem is only when one plugin needs to read a configuration of another plugin in Maven. The last time (a few months ago) I tried to google for the best and ideal way to achieve this goal, all I was able to find on Stack Overflow answers was to read the other plugin's effective project object model (POM), which is what Jib is doing. And last Friday, I happened to have a chance to look into [`native-image-maven-plugin`](https://github.com/oracle/graal/tree/master/substratevm/src/native-image-maven-plugin) for a work unrelated to this and found that it also reads configuration values from other plugins in the same way. Take a look at their code: [this](https://github.com/oracle/graal/blob/eb9d62211fc37a7bbbaa71f37b640f149792992d/substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java#L358-L366) and [this](https://github.com/oracle/graal/blob/eb9d62211fc37a7bbbaa71f37b640f149792992d/substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java#L343-L355).

So probably it's also what Oracle folks thought the only way. Therefore, if you were to use `native-image-maven-plugin` with `properties-maven-plugin`, you would run into the same problem. Unfortunately, there does not seem a way in Maven for one plugin to retrieve at runtime an actual MOJO instance of another plugin instantiated by Maven. This isn't a Jib-specific issue, it seems. There are some inherent limitations in using `properties-mave-plugin`, and I think this is the price you should take into account when deciding to use `properties-maven-plugin`. Maybe it might be simpler to use text-processing tools (such as `sed` or `awk`) to replace strings in `pom.xml` to attain your ultimate goal of keeping some values in a file.

**Comment by michaelze** [comment]
I see (there's really not much further to say 😉 

Thank you again for your thorough investigation and explanation, it's "close as won't fix" then, I guess?

**Comment by chanseokoh** [comment]
You're welcome. Yeah, unfortunately, I cannot really think of a good solution. If you happen to come with any idea in the future, let us know anytime. Thanks!
