### ISSUE TITLE
Support for docker buildArgs for CICD pipelines builds

### ISSUE THREAD

**Issue by marinoborges** [GoogleContainerTools/jib#2903]
**Environment**:

- *Jib version:* 2.6
- *Build tool:* Maven 3.6
- *OS:* Ubuntu 20.04

**Description of the issue**:
In my CI/CD pipeline, I want to build an image that depends on some variables that are dynamically passed by the pipeline. I used the Docker support for build time variables through the use of --build-arg so I could setup Wildfly Database Library and Datasource at build time.

Is there a way to support --build-arg in jib in the same way as --env is supported?

I found this related issue #1806 and this specific demand was not mentioned. Only ONBUILD related demand.

**Expected behavior**:
Would like to see some config in the <container> section
```
...
<build-args>
  <arg1>value1</arg1>
  <arg2>value2</arg2>
</build-args>
...
```

**Comment by chanseokoh** [comment]
Hi @marinoborges,

I am a bit confused, because jib doesn't make use of Docker or `Dockerfile`. Can you elaborate on what you are trying to do?

If you want to dynamically configure various parameters at build time, there are many options in Maven and Jib, e.g., using Maven profiles, general system properties, Maven project properties, or just Jib-specific system properties.

**Comment by marinoborges** [comment]
@chanseokoh You are right. There is no way to use the build args in the build process using JIB, since there is no `Dockerfile` or `RUN` commands involved. Thanks for your answer.
