### ISSUE TITLE
Avoid docker pull limit rate policy - maven jib:build should use image local from Node first

### ISSUE THREAD

**Issue by dungnt081191** [GoogleContainerTools/jib#2933]
HI everyone, 
In GitlabCI ( use Gitlab runner kubernetes executor). I have problem in pulling base image from Docker hub to build image using maven jib, here my examples:
```
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>2.5.2</version>
                <configuration>
                    <from>
                        <image>adoptopenjdk/openjdk8:jdk8u232-b09-alpine-slim</image>
                    </from>
                    <container>
                        <jvmFlags>
                            <jvmFlag>-Dfile.encoding=UTF-8</jvmFlag>
                        </jvmFlags>
                        <creationTime>USE_CURRENT_TIMESTAMP</creationTime>
                    </container>
                    <allowInsecureRegistries>true</allowInsecureRegistries>
                </configuration>
            </plugin>
```

When build image use docker runtime command : *mvn clean package -DkipTests jib:dockerBuild -Dimage=image-test-name:v1.0.0*
in this case:  maven will search & use image adoptopenjdk/openjdk8:jdk8u232-b09-alpine-slim from my local PC -->> it's my expected.

*BUT* 
*in case* : when build image use maven jib build command : *mvn clean package jib:build -Djib.to.auth.username="username" -Djib.to.auth.password="password" -Djib.to.image=path/registry/private -Djib.to.tags=tag-name-here*

*maven jib plugin always pull image from docker hub and show error log: *
```
Job failed: image pull failed: rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Another information : 
- gitlab runner kubernetes can pull image from Docker hub
- gitlab runner kubernetes run with previllige = true ( can use docker.sock of host machine (vm)
- gitlab runner install by helm official

**Comment by chanseokoh** [comment]
Hi @dungnt081191,

> When build image use docker runtime command : _mvn clean package -DkipTests jib:dockerBuild -Dimage=image-test-name:v1.0.0_
> in this case: maven will search & use image adoptopenjdk/openjdk8:jdk8u232-b09-alpine-slim from my local PC -->> it's my expected.

This is not true. Whether using `jib:build` or `jib:dockerBuild`, Jib always checks images on Docker Hub (and pull new images when they are updated). In order to make Jib use images in a local Docker daemon, you must explicitly designate it with the `docker://` prefix, e.g., by `<image>docker://adoptopenjdk/openjdk8:jdk8u232-b09-alpine-slim</image>`. It's probably that on your PC, you are not hitting the Docker Hub pull rate limit.

FYI, there are ways to prevent Jib from checking an up-to-date base image, given that you have already cached the image at least once: https://stackoverflow.com/a/61190005/1701388 (However, if you are not persisting the Jib base image cache across CircleCI builds, this may not apply to you.)

In light of the recent Docker Hub rate limit, we are looking into what Jib can do further to improve the user experience. Perhaps we should prioritize supporting registry mirrors (#1551).

---

BTW, the latest Jib is 2.7.0.

**Comment by chanseokoh** [comment]
I'll close the issue, but feel free to update if you have further questions or feedback.

**Comment by dungnt081191** [comment]
thanks @chanseokoh , i got it. the way i prevent docker pull rate limit is use sha256 hash instead if common tag , great

**Comment by chanseokoh** [comment]
@dungnt081191 FYI, to better support the users hitting the Docker Hub rate limiting, we implemented the registry mirror feature, which is now live with the Jib 2.8.0 release. Check out this [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-am-hitting-docker-hub-rate-limits-how-can-i-configure-registry-mirrors) to learn how to configure it.
