### ISSUE TITLE
failed because: Registry may not support pushing OCI Manifest or Docker Image Manifest Version 2, Schema 

### ISSUE THREAD

**Issue by manju-bala** [GoogleContainerTools/jib#3021]
Hi Team,

we are getting below error  intermittently.  

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':serviceproblem:consumer:jib'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Tried to push image manifest for artifactory/../../ but failed because: Registry may not support pushing OCI Manifest or Docker Image Manifest Version 2, Schema 2 | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new

**Comment by chanseokoh** [comment]
Hi @manju-bala,

The error is due to [the server returning `MANIFEST_INVALID` or `TAG_INVALID`](https://github.com/GoogleContainerTools/jib/blob/401df0f75eda65775fe07acd59facefb34f32535/jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPusher.java#L95-L120). The code is the only place we through that specific error message.

If you are getting the error intermittently, almost certainly it's an issue of the registry (seems Artifactory here). In the past years, we've occasionally got this type of errors where a major registry server (such as Quay.io, Sonatype Nexus, Artifactory, etc) intermittently says a manifest that Jib built is invalid when there's a high level of concurrency. All of such cases that were resolved turned out to be that there was a bug in a server. (For example, https://github.com/GoogleContainerTools/jib/issues/2470#issuecomment-630203903, #2372, and #1986). Jib throws a high level of concurrency, and given the circumstances, I highly suspect it's an issue in Artifactory.

Probably best to file a bug against Artifactory. We can assist you in proving that Jib is working correctly. Go over #2470 carefully and understand how the user provided us with detailed logs, what could be a workaround, and how the issue got resolved eventually. We can help you in the same way.

**Comment by chanseokoh** [comment]
@manju-bala any update on this?

**Comment by chanseokoh** [comment]
Closing the issue due to long inactivity. But as I explained, I'm leaning toward a bug in Artifactory. Please update here if you need further assistance.
