### ISSUE TITLE
Support for relocating classes in mvn

### ISSUE THREAD

**Issue by pratikmallya** [GoogleContainerTools/jib#3027]
Essentially, would like to see support for [relocating classes](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html). This is often used by hadoop users as they need to work with different versions of Guava for different dependencies.

An example of how this looks like for a project I work on today:
```xml
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-shade-plugin</artifactId>
          <version>3.2.4</version>
          <executions>
            <execution>
              <phase>package</phase>
              <goals>
                <goal>shade</goal>
              </goals>
              <configuration>
                <relocations>
                  <relocation>
                    <!-- We want to shade google provided libraries as they don't work well with hadoop ones -->
                    <pattern>com.google</pattern>
                    <shadedPattern>shaded.com.google</shadedPattern>
                  </relocation>
                </relocations>
                <filters>
                  <filter>
                    <artifact>*:*</artifact>
                    <excludes>
                      <exclude>META-INF/LICENSE</exclude>
                      <exclude>META-INF/*.SF</exclude>
                      <exclude>META-INF/*.DSA</exclude>
                      <exclude>META-INF/*.RSA</exclude>
                    </excludes>
                  </filter>
                </filters>
                <createDependencyReducedPom>false</createDependencyReducedPom>
              </configuration>
            </execution>
          </executions>
        </plugin>
      </plugins>
```
But the maven shade plugin always produces a uber jar, and I'm not sure how to only relocate classes without creating the uber jar.

**Comment by chanseokoh** [comment]
Hi @pratikmallya,

Although it could be a useful feature, it's hard to imagine that Jib will add a built-in support for that. Shading is a complicated and daunting task, and we don't want to be a plugin that embeds the workings of many years of maven-shade-plugin. Even if we intended to do so, we don't have the confidence that we'll ever make it work correctly. Better to leave the job to what maven-shade-plugin can best do.

A workaround I can think of (which I haven't tested myself):

1. Unzip the shaded jar (e.g., https://stackoverflow.com/a/37680575/1701388) into, say, `target/exploded-shaded-jar`.
2. Copy the entire contents of `target/exploded-shaded-jar` into a directory (e.g., `/shaded-app`) in an image by configuring [`<extraDirectories>`](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#adding-arbitrary-files-to-the-image).
3. Set [`<container><extraClasspath>`](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#container-object) to include `/shaded-app` in the Java runtime classpath (or just override `<entrypoint>`).
4. Configure the [Jib Layer-Filter extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-maven) to remove `/app` (where Jib originally puts all the classes, resources, dependencies, etc). You should fine-tune image layering with the extension to create multiple layers like what Jib does (i.e., a layer for your application classes, another for dependencies, and so on). We strongly discourage creating a single layer for the entire uber jar contents.

If this still sounds complicated and performance is not your concern, perhaps you can try `<containerizingMode>packaged` to have Jib just containerize the shaded uber jar. (You may have to do additional configuration for maven-jar-plugin and/or maven-shade-plugin so that Jib can pick up the shaded jar instead of the original jar. Haven't tested this myself, so I can't vouch. But even if you can't make Jib to pick up the uber jar, you can still copy it and remove the original jar in the way described above.) However, we strongly discourage containerizing a uber jar or creating a single layer for the entire uber jar contents; it can significantly slow down your edit-build-test dev cycle.

**Comment by chanseokoh** [comment]
As commented earlier, it's out of the scope of Jib. I'm closing the issue, but anyone, feel free to give us feedback.
