### ISSUE TITLE
Timeout on Artifactory when pushing a small container config JSON

### ISSUE THREAD

**Issue by mr-exz** [GoogleContainerTools/jib#3146]
**Environment**:

- *Jib version:* 2.8.0,2.7.1
- *Build tool:* maven
- *OS:* CentOS

**Description of the issue**:
Image with layers which contain ~200MB cannot be pushed.

**Expected behavior**:
It should be pushed because push over `docker push` works as expected.

**Steps to reproduce**:
  1. make image with fat layers at least one layer should be 200mb
  2. perform pushing ver jib

**`jib-maven-plugin` Configuration**: 
```xml
default one
```

**Log output**: 
```
[DEBUG] TIMING	pushBlob
[DEBUG] 	TIMING	pushBlob POST sha256:8446047073737851b91f598b5d551e2d5a1e0de81e7fa3687d0d020714eacfeb
[DEBUG] 	TIMED	pushBlob PATCH sha256:8446047073737851b91f598b5d551e2d5a1e0de81e7fa3687d0d020714eacfeb : 36.058 ms
[ERROR] [31;1mI/O error for image [docker/service]:[0m
[ERROR] [31;1m    java.net.SocketTimeoutException[0m
[ERROR] [31;1m    Read timed out[0m
[DEBUG] 	TIMED	pushBlob POST sha256:8446047073737851b91f598b5d551e2d5a1e0de81e7fa3687d0d020714eacfeb : 120131.764 ms
[DEBUG] TIMED	pushBlob : 120168.162 ms
[DEBUG] TIMED	Pushing BLOB digest: sha256:8446047073737851b91f598b5d551e2d5a1e0de81e7fa3687d0d020714eacfeb, size: 11396 : 120207.379 ms
[DEBUG] TIMED	Pushing container configuration : 120231.589 ms
[DEBUG] TIMED	Building and pushing image : 124849.373 ms
```

**Comment by mpeddada1** [comment]
Hey @mr-exz, I'm having a hard time reproducing this issue locally. Looking at this error message:
```
[ERROR] �[31;1m    java.net.SocketTimeoutException�[0m
[ERROR] �[31;1m    Read timed out�[0m
```
I wonder if it could be that your network is slow and Jib is timing out sooner than you'd like. What happens if you increase the Java net timeout value with `mvn compile jib:build -Djib.httpTimeout=7200000`, for example?

And it is also worth taking a look at #2014 as it discusses operation time outs in great detail.

**Comment by t-kap** [comment]
With -Djib.httpTimeout it just hangs forever at this phase:
`Mar 18, 2021 8:49:14 PM com.google.api.client.http.HttpRequest execute
CONFIG: -------------- REQUEST  --------------
POST https://docker.mycompany.com/v2/mycompanyservice/blobs/uploads/?mount=sha256:63a536c6d6a6fb4f9cee101989592fe839018c74457c1450772065202ae89eca&from=mycompany-docker-java
Accept: 
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: jib 2.8.0 jib-maven-plugin Google-HTTP-Java-Client/1.38.1 (gzip)

Mar 18, 2021 8:49:14 PM com.google.api.client.http.HttpRequest execute
CONFIG: curl -v --compressed -X POST -H 'Accept: ' -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: jib 2.8.0 jib-maven-plugin Google-HTTP-Java-Client/1.38.1 (gzip)' -- 'https://docker.mycompany.com/v2/mycompanyservice/blobs/uploads/?mount=sha256:63a536c6d6a6fb4f9cee101989592fe839018c74457c1450772065202ae89eca&from=mycompany-docker-java'
Mar 18, 2021 8:49:14 PM com.google.api.client.http.HttpResponse <init>
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 202 Accepted
x-jfrog-version: Artifactory/7.15.4 71504900
x-artifactory-id: 979b1de253662c49:-7a5606ce:17834f5bbf2:-8000
x-artifactory-node-id: repo
docker-distribution-api-version: registry/2.0
docker-upload-uuid: c26d0073-2dfc-4506-9564-26fdbaa88f9f
location: https://docker.mycompany.com/v2/mycompanyservice/blobs/uploads/c26d0073-2dfc-4506-9564-26fdbaa88f9f
content-length: 0
date: Thu, 18 Mar 2021 17:49:13 GMT
strict-transport-security: max-age=16000000; includeSubDomains; preload;

Mar 18, 2021 8:49:14 PM com.google.api.client.http.HttpRequest execute
CONFIG: -------------- REQUEST  --------------
PATCH https://docker.mycompany.com/v2/mycompanyservice/blobs/uploads/c26d0073-2dfc-4506-9564-26fdbaa88f9f
Accept: 
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: jib 2.8.0 jib-maven-plugin Google-HTTP-Java-Client/1.38.1 (gzip)
Content-Type: application/octet-stream

Mar 18, 2021 8:49:14 PM com.google.api.client.http.HttpRequest execute
CONFIG: curl -v --compressed -X PATCH -H 'Accept: ' -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: jib 2.8.0 jib-maven-plugin Google-HTTP-Java-Client/1.38.1 (gzip)' -H 'Content-Type: application/octet-stream' -d '@-' -- 'https://docker.mycompany.com/v2/mycompanyservice/blobs/uploads/c26d0073-2dfc-4506-9564-26fdbaa88f9f' << $$$
Mar 18, 2021 8:49:15 PM com.google.api.client.util.LoggingByteArrayOutputStream close
CONFIG: Total: 11,396 bytes
Mar 18, 2021 8:49:15 PM com.google.api.client.util.LoggingByteArrayOutputStream close
CONFIG: {"created":"1970-01-01T00:00:00Z","architecture":"amd64","os":"linux","config":{****************`

As a workaround I have to change jib version to 1.3
It always works as expected

**Comment by mr-exz** [comment]
@mpeddada1 for sure it is not network issue, since on same host in parallel i can execute docker push and it will be successful, of same image just without jib

**Comment by mpeddada1** [comment]
Right so `docker push` behaves differently from Jib. Unlike `docker`, Jib doesn’t retry when the first attempt at pushing a layer fails and Jib also pushes a whole layer as opposed to doing [chunked uploads](https://docs.docker.com/registry/spec/api/) as described in [#2014 (comment)](https://github.com/GoogleContainerTools/jib/issues/2014#issuecomment-534154014). This is an open issue and can be found in #1409. Therefore, this current drawback can cause delays in uploading the layer and eventually a timeout (which you have come across). 

If you are blocked at the moment, as a one-time workaround you can build your image to your local Docker daemon and then do a `docker push`. 

In the meantime, can you also send us the full HTTP logs with debug logs enabled (instructions can be found [here](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-can-i-examine-network-traffic)) so that we can better understand this behavior and investigate further?

**Comment by mpeddada1** [comment]
Just checking in: 
> In the meantime, can you also send us the full HTTP logs with debug logs enabled (instructions can be found [here](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-can-i-examine-network-traffic)) so that we can better understand this behavior and investigate further?

Any updates on this question? Did the workaround work okay?

**Comment by mr-exz** [comment]
Workaround with with changing jib version to 1.3 is working
right now provide other logs i cannot, we need prepare demo stand - so it will take some time

**Comment by chanseokoh** [comment]
@infobip-ci can you provide a full log. There's something that doesn't add up in the log you uploaded, so that's why we are asking for a full HTTP logs.

**Comment by mr-exz** [comment]
Guys any news ?

**Comment by mzagar** [comment]
@chanseokoh i managed to reproduce this and get logs - looks like read timeout occurs when pushing payload of only 11566 bytes.
using maven 3.8.1, adopt-openjdk16, jib 3.1.2

Strangely, when I test on some other project where I added layer >250MB in size timeout does not happen.
But on this project I can consistently reproduce this behavior.

[maven-jib-312-read-timeout-log.txt](https://github.com/GoogleContainerTools/jib/files/6907263/maven-jib-312-read-timeout-log.txt)

**Comment by chanseokoh** [comment]
@mzagar I wasn't able to find anything wrong from the log. That's very weird if it's always timing out when pushing a container config. I'm very curious if this is reproducible with other registries. You can easily spin up a [local registry](https://hub.docker.com/_/registry) and test it like this:
```
$ docker run -p8080:8080 registry:2
```
and then once it's up and running,
```
$ mvn -Djib.to.image=localhost:5000/myrepo -Djib.allowInsecureRegistries=true jib:build
```

**Comment by chanseokoh** [comment]
Correction: `-p5000:5000`, not `-p8080:8080`.

**Comment by mzagar** [comment]
I tried it several times running docker registry both on my laptop and on remote machine and I could not reproduce the socket read timeout.

Interestingly, in original issue report provided by @t-kap I can see that exact same Artifactory version is mentioned as in my repro case (`x-jfrog-version: Artifactory/7.15.4 71504900`) -- now starting to suspect this is some issue on artifactory side.

I opened [a ticket on JFrog for Artifactory](https://www.jfrog.com/jira/browse/RTFACT-26208) to see if something could be causing this from Artifactory side.

Currently we are working around this jib docker push issue by using fabric8 maven-docker-plugin for pushing docker image after it is built by jib.

**Comment by chanseokoh** [comment]
Ah, I also noticed another common symptom between @mzagar @t-kap and @mr-exz. As @mzagar mentioned, it's timing out when uploading a tiny container config JSON (of size 11566). For other fat layers, they uploaded successfully.

Also in @mr-exz's initial report, the timeout is when uploading a container config of size 11396. 
```
[DEBUG] 	TIMED	pushBlob POST sha256:8446047073737851b91f598b5d551e2d5a1e0de81e7fa3687d0d020714eacfeb : 120131.764 ms
[DEBUG] TIMED	pushBlob : 120168.162 ms
[DEBUG] TIMED	Pushing BLOB digest: sha256:8446047073737851b91f598b5d551e2d5a1e0de81e7fa3687d0d020714eacfeb, size: 11396 : 120207.379 ms
[DEBUG] TIMED	Pushing container configuration : 120231.589 ms
```
We mistakenly assumed from the user speculation that it is a general timeout issue for a large layer.

Also from @t-kap's log, the last request is to upload a container config.

---

Given that
   1) all other fat layers are successfully uploaded without a timeout
   2) always happens when uploading a small container config JSON (to be specific, `PATCH` step in a single blob upload operation that actually uploads the content of a JSON)
   3) some users report the exact same Artifactory version

I am learning toward more to an issue in Artifactory where it has a problem digesting a container config.

@mzagar is this reproducible regardless of setting `-Djib.serialize=true`?

**Comment by mzagar** [comment]
> is this reproducible regardless of setting -Djib.serialize=true? (BTW, thanks for creating a ticket and giving us the update.)
yes, the issue happens regardless of this setting.

**Comment by chanseokoh** [comment]
Thanks. Keep up updated for the Artifactory ticket.
