### ISSUE TITLE
AWS CLI v2 authentication to ECR

### ISSUE THREAD

**Issue by jakubgruber** [GoogleContainerTools/jib#3197]
**Environment**:

- *Jib version:* 2.7.1
- *Build tool:* Gradle 6.7.1
- *OS:* Ubuntu 20.04

**Description of the issue**:

I have updated AWS CodeBuild image to Ubuntu 20.04 which ships with AWS CLI version 2. The new AWS CLI has changed ECR login and I cannot authenticate Jib build now.

**Expected behavior**:

Previously, I could authenticate the Jib to ECR by `$(aws ecr get-login -no-include-email)` and then call `./gradlew jib`.

It has been deprecated now and recommended method is:

`aws ecr get-login-password | docker login --username AWS --password-stdin MY-REGISTRY-URL`
[(source)](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-ecr-get-login)

How do I reproduce `--password-stdin` in Jib environment?

Thank you

**Comment by chanseokoh** [comment]
Hi @jakubgruber, I see you closed the issue. Is it resolved? If so, how? I'm interested to hear. Or, was it not an issue actually?

**Comment by jakubgruber** [comment]
Hello @chanseokoh , it is not yet resolved but after submitting the issue, I somehow thought it was a stupid question and wanted to read the docs again.

I will try to solve it today and if I succeed, I would post a solution here, but if you would know how to combine AWS CLI v2 with Jib, it would be awesome!

**Comment by jakubgruber** [comment]
I have resolved the issue by rewriting the CI/CD pipeline. Your stackoverflow [comment](https://stackoverflow.com/a/64105567/6270838) helped me a lot to understand how the authentication works.

AWS CLI v1:
```
$(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
chmod +x ./gradlew
./gradlew jib --image=$ECR_REPO_URI:$IMAGE_TAG
```

AWS CLI v2:
```
JIB_ECR_USERNAME=AWS'
JIB_ECR_PASSWORD=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
chmod +x ./gradlew
./gradlew jib --image=$ECR_REPO_URI:$IMAGE_TAG -Djib.to.auth.username=$JIB_ECR_USERNAME -Djib.to.auth.password=$JIB_ECR_PASSWORD
```

Hopefully, someone will find this usefull.

**Comment by chanseokoh** [comment]
Thanks for the update. Very interesting. Just one thing, since you are passing the credentials on the command line, you may want to make sure that the command (hence the username and password) is not logged or stored in a shell history. You can easily eliminate risk in Gradle, e.g., if you set `jib.to.auth.username = System.getenv('JIB_ECR_USERNAME')` in `build.gradle`.

However, the following is supposed to just work. With the right `MY-REGISTRY-URL` (should be the `host[:port]` portion of `$ECR_REPO_URI`), it does `docker login`, which will store the credentials for the registry into `~/.docker/config.json`. Then Jib should be able to pick up the credentials for `MY-REGISTRY-URL`.
```
aws ecr get-login-password | docker login --username AWS --password-stdin MY-REGISTRY-URL
```

**Comment by jakubgruber** [comment]
Thank you for recommendation. Regarding the second solution you provided, what I find problematic is that I need to have docker installed and running which from my perspective contradicts usage of Jib (I know Jib handles much more, but still...).
