### ISSUE TITLE
How do I set permission in Directory.

### ISSUE THREAD

**Issue by aiman88** [GoogleContainerTools/jib#3273]
In DockerFile, I can set folder permission like below :

```
FROM registry-testing.xxxx.com/sandbox/gui-server:1.0.0-KBANKPOC-SNAPSHOT
USER root
RUN chmod 777 /home/www
USER www

```

But in **maven.jib,** i understand RUN is not recommended. So how can I do the same in **maven.jib** ?

**Comment by elefeint** [comment]
@aiman88 You can set permissions on any extra directories with `-Djib.extraDirectories.permissions` option (see [options summary](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extradirectories-object) and [arbitrary files docs](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#adding-arbitrary-files-to-the-image) for more details).

Would this meet your requirement?

**Comment by aiman88** [comment]
@elefeint , thanks for your reply..I was able to meet require by using other based images...but looking at the -`Djib.extraDirectories.permissions` it seem good also..

**Comment by chanseokoh** [comment]
Using `-Djib.extraDirectories.permissions` alone will probably not work for `/home/www`, as this directory is from the base image and not the directory created with the extraDirectories feature. I noticed you also posted the same Stack Overflow question (although there you indicated 755 instead of 777), and I've left an [answer](https://stackoverflow.com/q/67748735/1701388) for more details.
