### ISSUE TITLE
Error push docker image

### ISSUE THREAD

**Issue by Juanma97** [GoogleContainerTools/jib#3314]
When I push an image to docker hub, I retrieve this: 

[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.7.0:build (default-cli) on project common: Tried to retrieve authentication method for registry.hub.docker.com but failed because: registry returned error code 404; possible causes include invalid or wrong reference. Actual error output follows:

Openjdk11

The docker login is good.

I tried with jib 3.0.0 and 3.1.0 but nothing, I don't know what is the problem, or possible causes, any idea?

**Comment by dzou** [comment]
So I think should be supported but it's just a configuration error. 

Could you share more details about the command and configuration that you run and how you are referencing the image? Also please share the jib plugin configuration you're using in pom.xml, specifically the `jib.to.image` and `jib.from.image`.

Also you should use jib version 3.1.1; version 1.7.0 is quite old.

**Comment by chanseokoh** [comment]
The cause is an invalid or wrong `jib.{from|to}.image` reference. We sometimes see people unfamiliar with Docker (or Docker Hub) run into an issue like this when they use a wrong convention or syntax. If anyone experiences a similar issue (especially seeing 404), check out https://github.com/GoogleContainerTools/jib/issues/2561#issuecomment-678420281.
