### ISSUE TITLE
How to disable pushing of `latest` tag.

### ISSUE THREAD

**Issue by josephglanville** [GoogleContainerTools/jib#3330]
Hi,

When using a repository with tag immutability enabled (i.e ECR) attempting to re-push the `latest` tag causes the push to fail.

Is there currently a way to disable pushing this tag by default?
I tried overriding with `to.tags` but this only adds additional tags it doesn't prevent attempting to push `latest`.

**Comment by suztomo** [comment]
Checking...

**Comment by suztomo** [comment]
@josephglanville Would you specify a tag explicitly rather than (implicit) 'latest' tag?

The 'latest' tag is used when you don't specify a tag when pushing image to a repository. (c.f. https://github.com/GoogleContainerTools/jib/issues/2395)

When your repository still complains, please use this property:

> Just don't push or ignore the error if you are not building a different image. -Djib.skipExistingImages may be useful. Take a look at it.

(from https://github.com/GoogleContainerTools/jib/issues/3057 )

**Comment by josephglanville** [comment]
I see, I resolved the issue by setting the tag in `to.image` rather than in `to.tags`.

i.e: `to.image = "registry/repo/image:myTag"`

This successfully prevents `latest` from being pushed.

Thanks!
