### ISSUE TITLE
Disable update check by default

### ISSUE THREAD

**Issue by rmannibucau** [GoogleContainerTools/jib#3350]
com.google.cloud.tools.jib.plugins.common.globalconfig.GlobalConfigTemplate#disableUpdateCheck default should be true until user explicitly accept to enable it IMHO.

Setting the field to true is sufficient to solve that issue.

**Comment by meltsufin** [comment]
Many products have update checks on by default. It helps with security and getting bug fixes ASAP.
Closing because it work as intended.
If you think there is a way to offer changing default more easily, we're open to that.

**Comment by rmannibucau** [comment]
Well it only handles latest which will break as soon as you need major handling at least and it creates undesired requests which is impacting on low speed networks (phone).
Also note that most *libraries* (so it concerns jib-core, maven and gradle plugins) disable it by defaults (quartz did it some years ago: https://github.com/quartz-scheduler/quartz/commit/dfe1e5a3cc248e2a46a6ea55567aaa6dc8e15ca5) because it is noise for the consumer and does not integrate in the common dependency/security check flow.
Maven and gradle will use ossndex, blackduck, .... and maven version plugin for example which is already used for security fixes for all dependencies so something specific to JIB is not needed and does not help which the build does not fail (which is not an option right?)

**Comment by chanseokoh** [comment]
Appreciate your feedback. Certainly for jib-core, there's no update check implemented, as it doesn't make sense as a library. It's only for Jib build plugins and Jib CLI, and honestly, we don't consider Jib build plugins as libraries but as plugins for tools, so we think it's perfectly valid to implement an update check and at the same time having it turned on by default.

And this really helped the users upgrade fast. We continue to fix bugs, and it bothers us a lot and makes us sad to see some people running an old version of Jib that has bugs affecting their built images. We want people to build images better. Fortunately so far, we believe the upgrade checks have been working very well in that it really helped people up-to-date fast. To be honest, it is unlikely that we will disable it by default. Hope you understand.

BTW, network or build performance shouldn't be a concern. We've designed it very carefully so that it doesn't affect the main build at all. The update check runs in a completely separate and isolated thread, any kind of errors during the check will not affect the build, and it can even be that the update check is naturally terminated by JVM if the main build finishes earlier.

**Comment by rmannibucau** [comment]
Well I cant say much for gradle but on maven side it is really bothering (pollutes logs, triggers wrong alerts when logs are parsed and duplicates the widely used and standard tooling without an associated handling in general - trivial example is that such tools make the build fial whereas the checker does not).

Any hope it gets disabled at least for maven plugin since it is not well integrated with the ecosystem and not needed too.

**Comment by chanseokoh** [comment]
In that case, it's simple to disable it. You can set either a Maven property (possibly in `pom.xml`) or a system property `jib.disableUpdateChecks` (possibly on the command) to true, in addition to editing the global Jib config file. Given that there's are easy ways to turn it off, and based on what I said earlier, I don't feel we really have to flip the default value, sorry. One reason we added this Maven/system property was to make it as easy as possible to disable it for the users like in your situation. We want to help.
