### ISSUE TITLE
Feature request: allow to run smoketest before push

### ISSUE THREAD

**Issue by CodingSpiderFox** [GoogleContainerTools/jib#3354]
When building Spring Boot project's images, I just had a problem with a misconfig in the application.yaml where a wrong port was introduced and I didn't recognize that pre deploy. 

I would be nice if there was an option for jib to start the container image and make a HTTP GET to a given URL (e.g. "/api/health") to the container and check for HTTP 200 result. If it does not succeed, the build should fail

**Comment by elefeint** [comment]
This seems like something you could do as part of your maven/gradle build -- if you bind Jib's execution to the `package` phase,  then you can start the container and run integration tests in `verify` [phase](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#a-build-lifecycle-is-made-up-of-phases). You may be interested in the [Testcontainers project](https://www.testcontainers.org/) for running integration tests against a containerized dependency.

Jib's goal is lightweight container building without a dependency on Docker, which would be required for starting a container.

**Comment by CodingSpiderFox** [comment]
But how would I stop the image from being pushed when the smoketest fails if I bind Jib's execution to the package phase?

**Comment by elefeint** [comment]
You could [build a tarball](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#build-an-image-tarball) instead of pushing to a registry.

@chanseokoh There is no `--dry-run` or similar, right?

**Comment by CodingSpiderFox** [comment]
But then, if the smoketest succeeds, how would I push the images?

Run different profile for the tarball build first, then run the final profile? (I have 3 already for different tag names of the docker images (dev, staging, and ${project.version} for prod)

That would make the build config even more complex than it already is ... maybe there is another more simple solution?

**Comment by chanseokoh** [comment]
> I would be nice if there was an option for jib to start the container image and make a HTTP GET to a given URL (e.g. "/api/health") to the container and check for HTTP 200 result.

This definitely requires a container runtime (like Docker), and at this point, we have no plan to introduce any new features utilizing a container runtime (if such a runtime is available) going forward. I'd say it's on your own to devise effective tests, whether it's an integration test to actually run a container using Docker runtime, or a static structural test. Whether you bind Jib to the execution phase or not, I think that's not the point. You could do `./gradlew jibDockerBuild runMyTest jib`, for example (i.e., push an image to a Docker daemon, do something about it, and push if it's OK). Maven can do a similar thing. BTW, Any subsequent Jib operations (whether `jibDockerBuild`, `jibBuildTar`, or `jib`) should be super-fast, because everything is already cached. It's also a viable option to run multiple Gradle/Maven commands in succession if that helps.

> If it does not succeed, the build should fail

I found "failing a built" a bit contradicting. In order to effectively test or verify a built container image, then you have to build and store it somewhere in some format (whether or not you'll utilize a runtime). That is, you'll still have to either push it into a registry (could be a local registry, which is as easy as running [`docker run -p5000:5000 registry:2`](https://hub.docker.com/_/registry)), push it to a local Docker daemon (`jibDockerBuild`), or create an image tarball (`jibBuildTar`). That is, Jib build (i.e., image building) should succeed anyway.

But specifically in your example ("make a HTTP GET to a given URL"), I think you don't have to run this test after building an image. I think core functional tests like this should be part of your unit or integration tests for your app, unrelated to containerization. For Spring Boot specifically, this is easily testable and even the auto-generated helloworld demo does this kind of tests.

**Comment by CodingSpiderFox** [comment]
Yes, I agree except the last part. 

I had a problem where I had 4 profiles in my application.yml: local, dev, staging, prod. 
I was changing the port for "local" but didn't recognize I hadn't specified the port for the dev profile. 

To find such config mistakes, I think the only way is starting the container locally and making the request

**Comment by chanseokoh** [comment]
That's fair. Whatever it is, I'll just assume you have your reason to want to run a container after building it. So, as I explained earlier (which you seem to agree), you'll have to devise your own way to set up and run such tests, and I think currently there exist reasonable ways to make them work, perhaps with some clever use of Jib and Maven/Gradle bits.

For implementing any new feature around this, particularly one that utilizes a container runtime, unfortunately it's unlikely that we will work on it.
