### ISSUE TITLE
layers.idx ignored

### ISSUE THREAD

**Issue by tkgregory** [GoogleContainerTools/jib#3515]
**Environment**
* Windows 10 64 bit 
* Docker Deskstop  4.2.0 (70708)
* using `com.google.cloud.tools.jib` Gradle plugin version `3.1.4`

**Description**
When building a Docker image of a Spring Boot application using the Gradle plugin, Jib isn't respecting the contents of the *layers.idx* file.

My fat jar *BOOT-INF/layers.idx* contains:

```
- "dependencies":
  - "BOOT-INF/lib/"
- "spring-boot-loader":
  - "org/"
- "snapshot-dependencies":
- "application":
  - "BOOT-INF/classes/"
  - "BOOT-INF/classpath.idx"
  - "BOOT-INF/layers.idx"
  - "META-INF/"
```

Once I've built the image with `./gradlew jibDockerBuild`, I'm inspecting the steps using `docker hsitory`. 
```
IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
5245ba16bf56   51 years ago   jib-gradle-plugin:3.1.4                         2.67kB    jvm arg files
<missing>      51 years ago   jib-gradle-plugin:3.1.4                         8.3kB     classes
<missing>      51 years ago   jib-gradle-plugin:3.1.4                         41.9MB    dependencies
<missing>      2 days ago     /bin/sh -c #(nop)  ENV JAVA_HOME=/usr/lib/jv…   0B
<missing>      2 days ago     |1 ZULU_REPO_VER=1.0.0-2 /bin/sh -c apt-get …   227MB
<missing>      2 days ago     /bin/sh -c #(nop)  ARG ZULU_REPO_VER=1.0.0-2    0B
<missing>      2 days ago     /bin/sh -c #(nop)  ENV LANG=en_US.UTF-8 LANG…   0B
<missing>      6 weeks ago    /bin/sh -c #(nop)  CMD ["bash"]                 0B
<missing>      6 weeks ago    /bin/sh -c #(nop) ADD file:5d68d27cc15a80653…   72.8MB
```

There is a *classes* and *dependencies* layer (*classes* should be called *application* as per *layers.idx*). The *spring-boot-loader* layer is missing.

I've validated this by inspecting the filesystem of a running container.

```
root@7000c85232be:/# ls -l /app
total 16
drwxr-xr-x 3 root root 4096 Jan  1  1970 classes
-rw-r--r-- 1 root root 2640 Jan  1  1970 jib-classpath-file
-rw-r--r-- 1 root root   35 Jan  1  1970 jib-main-class-file
drwxr-xr-x 2 root root 4096 Jan  1  1970 libs
```

**Expected behavior**:

I expect the produced image to have the layers as described in the *layers.idx* file within the *jar* as per [these docs](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#jib-cli).

> The default mode for containerizing a JAR. It will respect layers.idx in the JAR (if present) or create optimized layers in the following format:

**Steps to reproduce**:
  1. `git clone  https://github.com/tkgregory/spring-boot-api-example.git`
  2. `git checkout jib-issue`
  3. `./gradlew jibDockerBuild`
  4. `docker history jib-test`

**Configuration**: 
```groovy
plugins {
//...
    id "com.google.cloud.tools.jib" version "3.1.4"
}

jib {
    from {
        image = 'azul/zulu-openjdk:17-jre'
    }
    to {
        image = 'jib-test'
    }
}
//...
```
(see full [build.gradle](https://github.com/tkgregory/spring-boot-api-example/blob/jib-issue/build.gradle))

**Additional information**

Note that the image actually runs fine. Looking forward to your feedback.

**Comment by mpeddada1** [comment]
Hi @tkgregory, thanks for the detailed description of the issue. This seems to be working as expected. 

Layering the JAR as per `layers.idx` is a feature that only applies to the [Jib CLI ](https://github.com/GoogleContainerTools/jib/tree/master/jib-cli)`jar` command. The Jib CLI `jar` command takes a JAR path as an input and creates an optimized image with the layers as described in the [link](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-does-the-jar-command-support-spring-boot-jars) that you mentioned. If you are looking to containerize a Spring Boot JAR then this might be an option for you. 

Otherwise, you may find the ["How are Jib applications layered?"](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-are-jib-applications-layered) section in the FAQ to be helpful if you want to learn more about how the Jib Gradle and Maven plugins create layers. If you're looking for more fine-grained layer control, then [Jib-Layer-Filter-Extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-gradle) is worth a look.

**Comment by tkgregory** [comment]
Thanks @mpeddada1 for the detailed explanation. I will take a look at the docs.
