### ISSUE TITLE
unable to fetch adoptopenjdk:11-jre-hotspot during publishing Docker image to Jfrog artifactory

### ISSUE THREAD

**Issue by amanarch96** [GoogleContainerTools/jib#3638]
**Environment**:

- *Jib version:* **3.2.1**
- *Build tool:* **Apache Maven 3.8.5**
- *OS:* **Ubuntu**

**Description of the issue**:
Facing issue while authenticating from jfrog artifactory for **adoptopenjdk:11-jre-hotspot**

![image](https://user-images.githubusercontent.com/101345527/162485278-52dd2136-9429-4869-a08b-ad89a6bedabe.png)

**Expected behavior**:
The authentication should be through and maven build should publish Docker image to Jfrog artifactory. Sample below:

![image](https://user-images.githubusercontent.com/101345527/162485033-69aaf025-5620-49b5-a4d9-edd06a9448d8.png)

**Steps to reproduce**:

  1. Maven build command: mvn -B -V -e -Dstyle.color=always clean package jib:buildTar \
  -Djib.from.image=jfrog-repo-path/adoptopenjdk:11-jre-hotspot \
  -Djib.outputPaths.tar=/home/runner/work/github-repo-name/docker-image.tar

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>jib-maven-plugin</artifactId>
	<version>3.2.1</version>
	<configuration>
		<from>
			<image>docker.org-name.com/adoptopenjdk:11-jre-hotspot</image>
		</from>
		<to>
			<image>docker-snapshots.org-name.com/org-name/path-to-repo/${project.artifactId}/${project.artifactId}:${project.version}-local</image>
		</to>
		<container>
			<jvmFlags>
				<jvmFlag>-noverify</jvmFlag>
				<jvmFlag>-XX:+AlwaysPreTouch</jvmFlag>
				<jvmFlag>-Djava.security.egd=file:/dev/./urandom</jvmFlag>
			</jvmFlags>
			<entrypoint>
				<command>bash</command>
				<arg>-c</arg>
				<arg>/entrypoint.sh</arg>
			</entrypoint>
			<environment>
				<SPRING_OUTPUT_ANSI_ENABLED>ALWAYS</SPRING_OUTPUT_ANSI_ENABLED>
			</environment>
			<creationTime>USE_CURRENT_TIMESTAMP</creationTime>
		</container>
		<extraDirectories>
			<paths>
				<path>src/main/jib/</path>
			</paths>
			<permissions>
				<permission>
					<file>/entrypoint.sh</file>
					<mode>755</mode>
				</permission>
			</permissions>
		</extraDirectories>
		<outputPaths>
			<tar>${project.build.directory}/${project.artifactId}-image.tar</tar>
			<digest>${project.build.directory}/${project.artifactId}-image.digest</digest>
			<imageId>${project.build.directory}/${project.artifactId}-image.id</imageId>
		</outputPaths>
	</configuration>
</plugin>
```

**Log output**: 

**Additional Information**:

**Comment by amanarch96** [comment]
Hi, Any updates will be appreciated.

**Comment by mpeddada1** [comment]
Hey @amanarch96, if Jib was able to retrieve credentials then it will say something like “Using credentials…” as described here: https://github.com/GoogleContainerTools/jib/blob/c419354aa42c4c8a2a32f93c1524d0b31b598979/docs/faq.md#what-should-i-do-when-the-registry-responds-with-unauthorized. You may also find [this](https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/README.md#authentication-methods) section on Authentication methods to be helpful. Additionally, we seem to be getting a 404 error (not found) instead of 401 (unauthorized) so it may not be an authentication issue. Please verify if the base image path has been entered correctly. To troubleshoot further, perhaps you could also try doing `docker pull <image reference>` to see if you're able to retrieve the image via docker cli.

**Comment by chanseokoh** [comment]
I don't this is a Jib issue but something wrong in the jfrog artifactory.

**Comment by zhumin8** [comment]
Closing as part of cleanup. Please re-open if it's still relevant.
