### ISSUE TITLE
publish gradle plugin to maven central

### ISSUE THREAD

**Issue by coopstah13** [GoogleContainerTools/jib#3719]
**Environment**:

- 3.2.1
- Gradle 7.4.2
- Linux

**Description of the issue**:
I would like to use precompiled script plugins with jib as documented here: https://docs.gradle.org/current/userguide/custom_plugins.html#applying_external_plugins_in_precompiled_script_plugins

The problem is there is no way for me to declare the dependency to the jib gradle plugin as it isn't published (the maven plugin is though).

**Expected behavior**:
The plugin is published as an artifact to maven central

**Steps to reproduce**:
See above link

**Comment by zhumin8** [comment]
The gradle plugin is published to the gradle repository here: https://plugins.gradle.org/plugin/com.google.cloud.tools.jib

**Comment by coopstah13** [comment]
I don't think that is enough. I need to be able to reference it as a dependency, as in the link above.

**Comment by coopstah13** [comment]
in the example from my link:
```
dependencies {
    implementation 'com.bmuschko:gradle-docker-plugin:6.4.0'
}
```
This plugin is published to maven central with those coordinates. Similarly, jib would need to be published to maven central as the maven plugin is today. https://search.maven.org/artifact/com.google.cloud.tools/jib-maven-plugin/3.2.1/maven-plugin

**Comment by chanseokoh** [comment]
Particularly for Gradle, it doesn't matter where an artifact is published. If it's on Maven, you would declare `mavenCentral()`. If on the Gradle Plugin Portal, you would declare `gradlePluginPortal()`, but that's even unnecessary because the repo is available by default. In fact, the Gradle Plugin Portal is a Maven repo, so you could even declare `maven { url "https://plugins.gradle.org/m2/" }`, which is again unnecessary.

So you should have no problem accessing it. The Maven coordinate is `gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:3.2.1`.

However, I wonder why you want the Jib Gradle plugin, as it is not intended to be consumed as a library but as a plugin. Could [Jib Core](https://github.com/GoogleContainerTools/jib/tree/master/jib-core) library be the right choice?

**Comment by coopstah13** [comment]
OK, so the piece that makes it work is declaring `gradlePluginPortal()` in `repositories`. It cannot otherwise resolve the plugin (I confirmed by adding and removing it). The point is to be able to define jib configuration centrally and reuse it in a multi-module project. Gradle lets you define build scripts and then apply them as plugins (check the link). I'll close this because it works if I add the plugin repository.

**Comment by chanseokoh** [comment]
> So you should have no problem accessing it. The Maven coordinates are `gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:3.2.1`.

For some unknown reason, the coordinates with the prefix `gradle.plugin` are no longer valid starting with 3.3.0. `com.google.cloud.tools:jib-gradle-plugin:3.3.0` without the prefix works though, which actually looks better.

**Comment by hfhbd** [comment]
> For some unknown reason, the coordinates with the prefix `gradle.plugin` are no longer valid starting with 3.3.0. `com.google.cloud.tools:jib-gradle-plugin:3.3.0` without the prefix works though, which actually looks better.

The coordinate change was the result of updating the gradle publish plugin https://github.com/GoogleContainerTools/jib/pull/3701
