### ISSUE TITLE
How to build image containing test classes & test resources?

### ISSUE THREAD

**Issue by sebastianhaberey** [GoogleContainerTools/jib#3739]
**Environment**:

- *Jib version:* 3.1.4
- *Build tool:* Gradle 7.3
- *OS:* macOS Monterey 12.5.1

**Description of the issue**:

Because our Java application uses a linux native library over JNI, we have a slightly modified linux / eclipse-temurin base image that additionally contains our native libraries. We use jib to build our application image based on this image. This works fine. 

Now we'd like to run our unit / integration tests in the same manner: by having jib build an image with all the required files, including test files and test resources, then run the tests by starting a container (maybe with a custom entrypoint).

Now naturally, the image created by jib doesn't contain test classes and resources. Is there a way to configure jib to include them as well?

**Comment by elefeint** [comment]
Jib tasks depend on the built-in gradle tasks that, in turn, depend on the [main source set](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_plugin_and_dependency_management). So normally, like you found, only the compile-time dependencies are packaged up and containerized.

You have two places where this behavior could be modified -- either changing Gradle main source set to include the test directory, or using Jib's [extraDirectories](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#adding-arbitrary-files-to-the-image) setting to add in the test branch.

**Comment by chanseokoh** [comment]
For Gradle, you can also set [`jib.configurationName`](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#extended-usage) to set a custom [Gradle configuration](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ConfigurationContainer.html).

**Comment by sebastianhaberey** [comment]
@elefeint and @chanseokoh thank you, I'll try to go from there!

**Comment by sschuberth** [comment]
@sebastianhaberey, have you succeeded in doing this and could you share your solution for Gradle? I'm particularly interested in how you actually *run* your tests. Because including all test classes / JARs (and their dependencies) in the Docker image probably is not enough, you also need a test runner, i.e. do what Gradle would usually do. Ideally, you would create a self-contained test runner that you could use as the entry-point for this special "test Docker image", and use just `docker run ...` on it to run the tests.
