### ISSUE TITLE
jib  mainClass

### ISSUE THREAD

**Issue by Ahejia** [GoogleContainerTools/jib#3790]
![image](https://user-images.githubusercontent.com/40256834/191923813-45ff9501-3185-446b-a89d-d494f0b5431d.png)
contain里面的mainClass找不到对应的启动类

**Comment by emmileaf** [comment]
From the screenshot it looks like you are building with gradle (please correct me if mistaken), so `container.mainClass` should be specified as a string, e.g. 'mypackage.MyApp' (instead of mypackage.MyApp - see [this example](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#example)).

**Comment by alicejli** [comment]
Closing due to lack of response.
