### ISSUE TITLE
`extraDirectories` from/into error message is swapped

### ISSUE THREAD

**Issue by AkselAllas** [GoogleContainerTools/jib#3803]
**Environment**:

- *3.2.0:* 
- *Gradle*
- *Ubuntu* 

**Description of the issue**:
```
  extraDirectories {
    paths {
      path {
        setFrom("build/path")
        into = "/app/build/path"
      }
    }
  }
```
Gives
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jib'.
> extraDirectories.paths contain "from" directory that doesn't exist locally: /app/build/path
```

**Expected behavior**:
It works

**Comment by mpeddada1** [comment]
@AkselAllas The directory (in the `from` section) needs to be present locally in order to be successfully added to the container with the extraDirectories feature (here is the [CHANGELOG](https://github.com/GoogleContainerTools/jib/blob/68d4e62702cd7a59df38601b0b07e7db2438d95d/jib-gradle-plugin/CHANGELOG.md#changed-3) that specifies this usage). Please verify if that is the case. Additionally, here is an [example](https://github.com/GoogleContainerTools/jib/blob/master/examples/java-agent/build.gradle) for reference. 

That being said, the error message itself is a little curious. It is interesting that it refers to the `from` attribute but mentions the path in the `into` attribute.  Would be able to share a small reproducer and the stacktrace of the exception that you are seeing?

**Comment by AkselAllas** [comment]
You're correct. My problem was that `from` folder didn't exist in CI/CD due to my own dependency logic failure. 

But the error message being swapped made me extra confused.

**Comment by AkselAllas** [comment]
Seems [this line](https://github.com/GoogleContainerTools/jib/blob/49936f256475379806d144db238c25afea73e7c7/jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java#L460) can get confused in my case?

```
      path {
        setFrom("build/path")
        into = "/app/build/path"
      }
```

![image](https://user-images.githubusercontent.com/26136082/193764816-6cbc5dbd-c72f-4c30-8a6c-f28ac3edb7ce.png)

**Comment by emmileaf** [comment]
Because the from path of `build/path` is specified relatively (and displayed as an absolute path in the error message), could it be that the two absolute paths for `from` and `into` happened to coincide (possibly in the case that `/app` is also the local project directory)?

**Comment by alicejli** [comment]
@emmileaf's conclusion appears to be correct - I just tested with the following:

```
extraDirectories {
    paths {
      path {
        setFrom("build/path")
        into = "/potato/apple"
      }
    }
  }
```
and the error message is:

`extraDirectories.paths contain "from" directory that doesn't exist locally: /home/alicejli/jib/examples/java-agent/build/path`, which is correct.
