### ISSUE TITLE
Timeout in push

### ISSUE THREAD

**Issue by kareemfcih** [GoogleContainerTools/jib#3959]
**Environment**:

- *Jib version:* 3.3.0
- *Build tool:* Maven
- *OS:* Linux

**Description of the issue**:
I'm using jenkins to build and push images to ECR, and i'm facing a timeout after about 18 minutes, the server connection maybe slow but i want to increase the timeout to take its time, i added  -Djib.httpTimeout=99720000 to the build stage but didn't work

```
stage('Docker Build'){
      javaHome= tool 'JDK8'
      mvnHome = tool 'Maven_instance'
       withEnv(["MVN_HOME=$mvnHome","JAVA_HOME=$javaHome"]) {
              echo "Building docker image"
              sh '"$MVN_HOME/bin/mvn" -f ${WORKSPACE}/${Module} clean compile -Djib.httpTimeout=99720000 jib:build'
       }
  }

```

**Steps to reproduce**:

  1. the job execute command `/var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_instance/bin/mvn -f /var/lib/jenkins/workspace/BE_DOCKER_PIPELINE/Web/pom.xml clean compile -Djib.httpTimeout=99720000 jib:build`
  2. it builds and stuck at `Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, com.asset.ir.app.MainApp]` for sometime
  3. then it timeout```[ERROR]     java.net.SocketException
[ERROR]     Connection timed out (Write failed)
[WARNING] PATCH [https://......dkr.ecr](https://......dkr.ecr.eu-west-1.amazonaws.com/v2/.....)```

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>jib-maven-plugin</artifactId>
  <version>3.3.0</version>
  <configuration>
	  <from>
		  <image>eclipse-temurin:8</image>
	  </from>
	  <to>
		  <image>AWS-REPO-URL</image>
		  <tags>
			  <tag>staging-latest</tag>
		  </tags>
	  </to>
  </configuration>
</plugin>
```

**Log output**: 

```
[INFO] Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, com.asset.ir.app.MainApp]
[WARNING] PATCH https://......dkr.ecr.eu-west-1.amazonaws.com/v2/.........3c failed and will NOT be retried
[ERROR] I/O error for image [......dkr.ecr.eu-west-1.amazonaws.com/.....]:
[ERROR]     java.net.SocketException
[ERROR]     Connection timed out (Write failed)
[WARNING] PATCH https://.... failed and will NOT be retried
[ERROR] I/O error for image [....dkr.ecr.eu-west-1.amazonaws.com/....]:
```

Thank you

**Comment by emmileaf** [comment]
Are you consistently observing this timeout issue at about 18 minutes, and are you expecting the image push to take around this time? (Since `-Djib.httpTimeout` has a [default value of 20000](https://github.com/GoogleContainerTools/jib/blob/e50b825cfe92f0bc3a690de40444485e6fae51e2/jib-core/src/main/java/com/google/cloud/tools/jib/global/JibSystemProperties.java#L47), which would be roughly 30 seconds, I wonder if there is something else failing or imposing this timeout.)

You might find [this section of the faq](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-can-i-examine-network-traffic) helpful for debugging network connection issues.
