### ISSUE TITLE
Allow short caching of images

### ISSUE THREAD

**Issue by larsgrefer** [GoogleContainerTools/jib#4123]
This is a feature request:

Provide an option to limit/cache image up-to-date checks.

This would be an additional option to mitigate the rate-limiting problems with Docker Hub as described in #3042 and #2933.

Context: We have different multi-module Gradle projects that build multiple Images each with jib. Our CI server hit the rate limit at Docker Hub. While looking into this, I noticed that only 3 Images are effectively used from Docker Hub, but these are checked for updates very frequently.

**Option A:** Avoid update-to-date checks during the same Gradle (or Maven) invocation. In our case, one call to `./gradlew jib` invokes up to 10 jib tasks, which all use the same base image. This causes 10 up-to-date check requests to Docker Hub for the same image in very quick succession.

**Option B:** Allow a "max-age" to be configured for the cached images, so no up-to-date check is performed, if the last one was only X minutes ago.

Something like this already seems to be implemented with the offline mode, but instead of completely blocking online access I only want to limit it to once per image and build-invocation or once per image and timeframe.

**Comment by mpeddada1** [comment]
@larsgrefer Thanks for the detailed context! As mentioned in https://github.com/GoogleContainerTools/jib/issues/2933#issuecomment-742742828, there are already ways to handle the docker rate limit issue - 1) By pinning the base image a digest instead of always pulling the latest image and 2) by leveraging registry mirrors. You may also find this [FAQ entry ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-am-hitting-docker-hub-rate-limits-how-can-i-configure-registry-mirrors) to be helpful which contains more information on how the Docker rate limit issue can be addressed.
