### ISSUE TITLE
Using extraDirectories.includes in kotlin dsl

### ISSUE THREAD

**Issue by RestfulBlue** [GoogleContainerTools/jib#4127]
Hello! is it possible to use extraDirectories.includes in kotlin dsl?
No matter how i try, i always get unsupported operation exception,

for example
```
                        path {
                            setFrom(file.parentFile)
                            includes.get().add("version.txt")
                            into = "/app"
                        }
```

also, as long as i could see in repository, implementation has only getters and no setters 
my current gradle version is 8.0.2
jib version is 3.4.0

**Comment by emmileaf** [comment]
@RestfulBlue You might find #3668 relevant to this question! There are no setters in the implementation because they are generated for each `Property` type (Gradle [docs](https://docs.gradle.org/current/userguide/lazy_configuration.html#lazy_properties) for reference) - in Groovy DSL this allows for the assignment (=) operator, but for Kotlin DSL, the `set()` method will need to be used instead.

**Comment by RestfulBlue** [comment]
oh, i see, thank you!

**Comment by chanseokoh** [comment]
FYI, Gradle 8.2 now allows direct assigning: https://github.com/GoogleContainerTools/jib/issues/3668#issuecomment-1781232502
