### ISSUE TITLE
Simplify TarStreamBuilder#addEntry() to deal with bytes

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#630]
From https://github.com/GoogleContainerTools/jib/pull/627#pullrequestreview-137528865

`TarStreamBuilder#addEntry(String content, String fileLocation)` seems to be called by `ImageToTarballTranslator#toTarballBlob()` to add container configuration and manifest files. Oddly the content of these files is passed as a String such that the `TarStreamBuilder` is responsible for performing an text to byte encoding. Rather than provide two variants of `TarStreamBuilder#addEntry()`, why don't we just pass the file contents as `byte[]` and let `toTarballBlob()` deal with the encoding?

**Comment by elharo** [comment]
Agreed. Something looks very off here. Output streams should work on bytes, not strings. Passing file content as a string is a huge red flag.

**Comment by coollog** [comment]
I think the original point of using `String` as a parameter type is to prevent callers from accidentally using the `addEntry(String content, String fileLocation)` signature for files (as opposed to `addEntry(TarArchiveEntry entry)`), where they accidentally read the file into a `byte[]` and then call this method. For files, the `addEntry(TarArchiveEntry entry)` signature should be used so that files are never read into memory.
