### ISSUE TITLE
support configuring a Docker HEALTHCHECK

### ISSUE THREAD

**Issue by jack-kerouac** [GoogleContainerTools/jib#676]
**Description of the issue**:
Support configuring a [Docker HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) for the resulting Docker image.

**Expected behavior**:
The Jib configuration should allow adding a Docker `HEALTHCHECK`, including `interval`, `timeout`, `start-period`, `retries`, and `CMD` to run.

**Comment by werty1st** [comment]
Hello @coollog, i would like to question your assumtion, that by design, a shell is needed to run a HEALTHCHECK.

The docs state that 
> The command after the CMD keyword can be either a shell command (e.g. HEALTHCHECK CMD /bin/check-running) or an exec array (as with other Dockerfile commands; see e.g. ENTRYPOINT for details).

So why should 
`HEALTHCHECK ["java", "-cp", "/app/resources/:/app/classes/:/app/libs/*", "com.company.content.feed.consumer.ContentFeedConsumerApplication", "health"]`
not work?

**Comment by swift1911** [comment]
HEALTHCHECK is very important for check container is healthy or not , especially for java service

**Comment by tburch** [comment]
This would be super useful to have with [ECS health checks](https://aws.amazon.com/about-aws/whats-new/2018/03/amazon-ecs-supports-container-health-checks-and-task-health-mana/). I'd love to see support added.
