### ISSUE TITLE
Jib should respect `—offline`

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#718]
**Description of the issue**:

Jib should respect the `—offline` flags for Gradle and Maven: jib should use the cached _from_ image,  erroring if it doesn't exist, and `:build` should fail.  This might help address some of the issues seen by users in high-latency zones (e.g. #648, #713).

**Comment by coollog** [comment]
This would actually be a fairly involved change since Jib doesn't currently cache the base image manifests. To resolve this issue, Jib would need to:

- cache base image manifests, with the image reference they refer to
- cache the container configuration for those base images as well
- fetch cached base image manifests via image references
- only do this when `--offline` is set, but still pull manifests if `--offline` is not set to check for any updates

**Comment by YangGuang001** [comment]
recently, I use the jib, but my base image is very big, it takes me a long time to generate the image.
I think the Jib only need to check the manifests.

**Comment by coollog** [comment]
Hi @YangGuang001 , the initial run of Jib will download the entire base image. However, subsequent runs should use the cached base image and should not require re-downloading the base image layers. Do your subsequent builds run faster?

**Comment by PierreBesson** [comment]
I must stress the importance of this issue. This is currently a pain point for a lot of JHipster users, especially those who don't have access to a private docker registry on their developer machines.
Currently, we have a big warning in our [jib usage docs](https://www.jhipster.tech/docker-compose/#3) to educate our users on this problem.

**Comment by chanseokoh** [comment]
> Currently, we have a big warning in our [jib usage docs](https://www.jhipster.tech/docker-compose/#3)

@PierreBesson I've read the warning. The warning says the build may fail because of network issues or because you are not logged in a Docker registry. Here are a few things I'd like to point out:
- You'll be using public images, so I don't think the build will fail because you are not logged in. I don't really get the warning.
- Even with `--offline`, the build will fail for the first time when Jib has not yet cached the base image. (Also note that Jib's cache has nothing to do with Docker's.) Your warning gives me the (false) impression that the build will not fail once Jib supports `--offline`, but I think this can be misleading.
- `exportDockerContext` has been removed and is no longer available in recent versions.

**Comment by PierreBesson** [comment]
Thanks for this explanation. I will rework this part of the docs to be more technically accurate. 
I see now that being logged in or not is not really the issue for public base images. I think people might still encounter problems with their proxies though.

> Also note that Jib's cache has nothing to do with Docker's.

I didn't know that, it seems important to explain this in our docs.

> Even with `--offline`, the build will fail for the first time when Jib has not yet cached the base image.

OK but this seems acceptable to me, however I think the main issue people have is that jib forces pulling the image when rebuilding even if already pulled which is different from the default `docker build` behavior.

> `exportDockerContext` has been removed and is no longer available in recent versions.

We will have to stop recommending this after migrating to jib 1.0.

**Comment by chanseokoh** [comment]
> however I think the main issue people have is that jib forces pulling the image when rebuilding even if already pulled which is different from the default `docker build` behavior.

For clarification, just in case: Jib caches images and does not pull already cached images. It is just that Jib always accesses the image metadata to check if there is an update imaged. But I admit this behavior is different from `docker build`. Rather, applying `--offline` would be similar to it.

**Comment by TadCordle** [comment]
@YangGuang001 @PierreBesson @bensonreg @chenlein @antarus @Imbai version 1.2.0 has been released with initial support for offline mode. You will still need to run Jib at least once in online mode to fully cache the base image, but afterwards, Jib will use the cached base image instead of downloading the manifest if you specify `--offline` in Maven/Gradle. It's also worth noting that you cannot build to a registry in offline mode; only the Docker daemon or a tarball.

We plan on looking into further improvements in the future, such as checking Docker's cache for the base image if it is missing from Jib's cache ([#1468](https://github.com/GoogleContainerTools/jib/issues/1468)), or even skipping the pull step altogether if the base image already exists on the target registry ([#1673](https://github.com/GoogleContainerTools/jib/issues/1673)).

**Comment by PierreBesson** [comment]
Great work @tadcordle. Congrats to the team for shipping ! This was an important feature for us. Thanks a lot !

**Comment by tonylook** [comment]
> I must stress the importance of this issue. This is currently a pain point for a lot of JHipster users, especially those who don't have access to a private docker registry on their developer machines.
> Currently, we have a big warning in our [jib usage docs](https://www.jhipster.tech/docker-compose/#3) to educate our users on this problem.

To solve this issue, you don't need to use --offline, you need to put `docker://imagename:tag` at the `<from><image>` tag in the pom.xml
