### ISSUE TITLE
Empty image cache metadata

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#799]
https://github.com/GoogleContainerTools/jib/issues/534#issuecomment-410630825

It's worth an investigation. Even if this happens only when there is a problem interacting with a registry, we should be able to have a correct cache metadata locally.

**Comment by coollog** [comment]
This is due to the build failing at the manifest push step, whereas cache metadata is currently written after build steps succeed. To resolve this, we would need to either 

1. Change cache metadata to be independent for each layer so that each can be written independently and during their respective build steps, or
1. Catch any failures during the build steps and write the cache metadata upon failure as well

I prefer approach 1) since it is more robust and less prone to possible cache corruption.

**Comment by chanseokoh** [comment]
@Hi-Fi FYI, the Jib cache metadata is just an Jib-internal data structure and has nothing to do with files actually used for the Docker or OCI image format.

**Comment by coollog** [comment]
This will be fixed by the new cache mechanism #878
